# -*- coding: utf-8 -*-
"""
quran_words.py
Quran-Grundwortschatz nach Haeufigkeit, in Lernstufen geordnet.

Zur Einordnung: Der Quran hat rund 78.000 Wortvorkommen, aber nur etwa
1.800 Wurzeln. Wenige Woerter tragen sehr viel Text:
    ~300 Woerter  ->  rund 70 % aller Vorkommen
    ~600 Woerter  ->  rund 80 %
   ~1000 Woerter  ->  rund 85-90 %

"level" ist die Lernreihenfolge, nicht die Wortart:
    1  Funktionswoerter und die absoluten Spitzenreiter - ohne sie geht kein Vers
    2  die haeufigsten Nomen
    3  die haeufigsten Verben
    4  Eigenschaften, Gottesnamen, weitere haeufige Woerter

"freq" steht NUR dort, wo die Zahl belastbar ist (die bekannten Spitzenwerte).
Wo sie fehlt, ist das Absicht - eine erfundene Zahl waere schlechter als keine.
Die Lernreihenfolge haengt an "level", nicht an "freq".

Kein Feld "spoken": Quranwoerter werden nicht in Pausalform gelernt.
"""

WORDS = [
    # ================= Stufe 1: Funktionswoerter und Spitzenreiter =========
    {"ar": "اللَّهُ", "de": "Allah, Gott", "root": "أ ل ه", "level": 1, "freq": 2699},
    {"ar": "مِنْ", "de": "von, aus", "root": "—", "level": 1, "freq": 3226},
    {"ar": "فِي", "de": "in", "root": "—", "level": 1, "freq": 1701},
    {"ar": "عَلَىٰ", "de": "auf, über", "root": "ع ل و", "level": 1},
    {"ar": "إِلَىٰ", "de": "zu, nach", "root": "—", "level": 1},
    {"ar": "عَنْ", "de": "von, über", "root": "—", "level": 1},
    {"ar": "مَعَ", "de": "mit", "root": "—", "level": 1},
    {"ar": "بَيْنَ", "de": "zwischen", "root": "ب ي ن", "level": 1},
    {"ar": "عِنْدَ", "de": "bei", "root": "ع ن د", "level": 1},
    {"ar": "بَعْدَ", "de": "nach", "root": "ب ع د", "level": 1},
    {"ar": "قَبْلَ", "de": "vor", "root": "ق ب ل", "level": 1},
    {"ar": "دُونَ", "de": "außer, unterhalb von", "root": "د و ن", "level": 1},
    {"ar": "غَيْرَ", "de": "nicht, anders als", "root": "غ ي ر", "level": 1},
    {"ar": "لَا", "de": "nicht (Verneinung)", "root": "—", "level": 1},
    {"ar": "مَا", "de": "was; nicht", "root": "—", "level": 1},
    {"ar": "لَمْ", "de": "nicht (Vergangenheit)", "root": "—", "level": 1},
    {"ar": "لَنْ", "de": "niemals (Zukunft)", "root": "—", "level": 1},
    {"ar": "إِلَّا", "de": "außer", "root": "—", "level": 1},
    {"ar": "إِنَّ", "de": "wahrlich", "root": "—", "level": 1},
    {"ar": "أَنَّ", "de": "dass", "root": "—", "level": 1},
    {"ar": "أَنْ", "de": "dass (vor Verb)", "root": "—", "level": 1},
    {"ar": "إِنْ", "de": "wenn", "root": "—", "level": 1},
    {"ar": "إِذَا", "de": "wenn, als", "root": "—", "level": 1},
    {"ar": "إِذْ", "de": "als (damals)", "root": "—", "level": 1},
    {"ar": "لَوْ", "de": "wenn (irreal)", "root": "—", "level": 1},
    {"ar": "ثُمَّ", "de": "dann, danach", "root": "—", "level": 1},
    {"ar": "أَوْ", "de": "oder", "root": "—", "level": 1},
    {"ar": "أَمْ", "de": "oder (in Fragen)", "root": "—", "level": 1},
    {"ar": "بَلْ", "de": "vielmehr, nein", "root": "—", "level": 1},
    {"ar": "لَٰكِنْ", "de": "aber", "root": "—", "level": 1},
    {"ar": "حَتَّىٰ", "de": "bis", "root": "—", "level": 1},
    {"ar": "قَدْ", "de": "bereits, gewiss", "root": "—", "level": 1},
    {"ar": "كُلُّ", "de": "jeder, alles", "root": "ك ل ل", "level": 1},
    {"ar": "بَعْضُ", "de": "einige, ein Teil", "root": "ب ع ض", "level": 1},
    {"ar": "مِثْلُ", "de": "gleich wie", "root": "م ث ل", "level": 1},
    {"ar": "هَٰذَا", "de": "dieser", "root": "—", "level": 1},
    {"ar": "هَٰذِهِ", "de": "diese", "root": "—", "level": 1},
    {"ar": "ذَٰلِكَ", "de": "jener, das", "root": "—", "level": 1},
    {"ar": "تِلْكَ", "de": "jene", "root": "—", "level": 1},
    {"ar": "أُولَٰئِكَ", "de": "jene (Mehrzahl)", "root": "—", "level": 1},
    {"ar": "الَّذِي", "de": "derjenige, der", "root": "—", "level": 1},
    {"ar": "الَّذِينَ", "de": "diejenigen, die", "root": "—", "level": 1},
    {"ar": "مَنْ", "de": "wer; derjenige, der", "root": "—", "level": 1},
    {"ar": "هُوَ", "de": "er", "root": "—", "level": 1},
    {"ar": "هِيَ", "de": "sie", "root": "—", "level": 1},
    {"ar": "هُمْ", "de": "sie (Mehrzahl)", "root": "—", "level": 1},
    {"ar": "أَنْتَ", "de": "du", "root": "—", "level": 1},
    {"ar": "أَنْتُمْ", "de": "ihr", "root": "—", "level": 1},
    {"ar": "نَحْنُ", "de": "wir", "root": "—", "level": 1},
    {"ar": "أَنَا", "de": "ich", "root": "—", "level": 1},
    {"ar": "إِيَّاكَ", "de": "Dich allein", "root": "—", "level": 1},
    {"ar": "كَيْفَ", "de": "wie", "root": "—", "level": 1},
    {"ar": "أَيْنَ", "de": "wo", "root": "—", "level": 1},
    {"ar": "مَتَىٰ", "de": "wann", "root": "—", "level": 1},
    {"ar": "هَلْ", "de": "(Fragewort)", "root": "—", "level": 1},
    {"ar": "لِمَ", "de": "warum", "root": "—", "level": 1},
    {"ar": "كَذَٰلِكَ", "de": "so, auf diese Weise", "root": "—", "level": 1},
    {"ar": "لَعَلَّ", "de": "damit, vielleicht", "root": "—", "level": 1},
    {"ar": "سَوْفَ", "de": "wird (Zukunft)", "root": "—", "level": 1},
    {"ar": "يَا", "de": "o (Anrede)", "root": "—", "level": 1},

    # ================= Stufe 2: die haeufigsten Nomen ======================
    {"ar": "رَبٌّ", "de": "Herr", "root": "ر ب ب", "level": 2, "freq": 975},
    {"ar": "يَوْمٌ", "de": "Tag", "root": "ي و م", "level": 2, "freq": 475},
    {"ar": "قَوْمٌ", "de": "Volk, Leute", "root": "ق و م", "level": 2, "freq": 383},
    {"ar": "آيَةٌ", "de": "Zeichen; Vers", "root": "أ ي ي", "level": 2, "freq": 382},
    {"ar": "رَسُولٌ", "de": "Gesandter", "root": "ر س ل", "level": 2, "freq": 332},
    {"ar": "عَذَابٌ", "de": "Strafe, Pein", "root": "ع ذ ب", "level": 2, "freq": 322},
    {"ar": "أَرْضٌ", "de": "Erde, Land", "root": "أ ر ض", "level": 2, "freq": 461},
    {"ar": "سَمَاءٌ", "de": "Himmel", "root": "س م و", "level": 2, "freq": 310},
    {"ar": "نَفْسٌ", "de": "Seele, Selbst", "root": "ن ف س", "level": 2, "freq": 295},
    {"ar": "كِتَابٌ", "de": "Buch, Schrift", "root": "ك ت ب", "level": 2, "freq": 261},
    {"ar": "حَقٌّ", "de": "Wahrheit, Recht", "root": "ح ق ق", "level": 2, "freq": 247},
    {"ar": "نَاسٌ", "de": "Menschen", "root": "ن و س", "level": 2, "freq": 241},
    {"ar": "سَبِيلٌ", "de": "Weg", "root": "س ب ل", "level": 2, "freq": 176},
    {"ar": "جَنَّةٌ", "de": "Garten, Paradies", "root": "ج ن ن", "level": 2, "freq": 147},
    {"ar": "نَارٌ", "de": "Feuer", "root": "ن و ر", "level": 2, "freq": 145},
    {"ar": "قَلْبٌ", "de": "Herz", "root": "ق ل ب", "level": 2, "freq": 132},
    {"ar": "آخِرَةٌ", "de": "Jenseits", "root": "أ خ ر", "level": 2, "freq": 115},
    {"ar": "دُنْيَا", "de": "Diesseits, Welt", "root": "د ن و", "level": 2, "freq": 115},
    {"ar": "رَحْمَةٌ", "de": "Barmherzigkeit", "root": "ر ح م", "level": 2, "freq": 114},
    {"ar": "عَبْدٌ", "de": "Diener, Knecht", "root": "ع ب د", "level": 2},
    {"ar": "أَمْرٌ", "de": "Angelegenheit; Befehl", "root": "أ م ر", "level": 2},
    {"ar": "خَيْرٌ", "de": "Gutes; besser", "root": "خ ي ر", "level": 2},
    {"ar": "شَرٌّ", "de": "Böses; schlimmer", "root": "ش ر ر", "level": 2},
    {"ar": "عِلْمٌ", "de": "Wissen", "root": "ع ل م", "level": 2},
    {"ar": "دِينٌ", "de": "Religion; Gericht", "root": "د ي ن", "level": 2},
    {"ar": "إِيمَانٌ", "de": "Glaube", "root": "أ م ن", "level": 2},
    {"ar": "عَمَلٌ", "de": "Werk, Tat", "root": "ع م ل", "level": 2},
    {"ar": "قَوْلٌ", "de": "Wort, Rede", "root": "ق و ل", "level": 2},
    {"ar": "مَالٌ", "de": "Besitz, Vermögen", "root": "م و ل", "level": 2},
    {"ar": "أَهْلٌ", "de": "Leute, Angehörige", "root": "أ ه ل", "level": 2},
    {"ar": "وَلَدٌ", "de": "Kind, Sohn", "root": "و ل د", "level": 2},
    {"ar": "بَيْتٌ", "de": "Haus", "root": "ب ي ت", "level": 2},
    {"ar": "يَدٌ", "de": "Hand", "root": "ي د ي", "level": 2},
    {"ar": "وَجْهٌ", "de": "Gesicht; Antlitz", "root": "و ج ه", "level": 2},
    {"ar": "عَيْنٌ", "de": "Auge; Quelle", "root": "ع ي ن", "level": 2},
    {"ar": "مَاءٌ", "de": "Wasser", "root": "م و ه", "level": 2},
    {"ar": "لَيْلٌ", "de": "Nacht", "root": "ل ي ل", "level": 2},
    {"ar": "نَهَارٌ", "de": "Tag (Tageslicht)", "root": "ن ه ر", "level": 2},
    {"ar": "شَمْسٌ", "de": "Sonne", "root": "ش م س", "level": 2},
    {"ar": "قَمَرٌ", "de": "Mond", "root": "ق م ر", "level": 2},
    {"ar": "جَبَلٌ", "de": "Berg", "root": "ج ب ل", "level": 2},
    {"ar": "بَحْرٌ", "de": "Meer", "root": "ب ح ر", "level": 2},
    {"ar": "مَوْتٌ", "de": "Tod", "root": "م و ت", "level": 2},
    {"ar": "حَيَاةٌ", "de": "Leben", "root": "ح ي ي", "level": 2},
    {"ar": "نُورٌ", "de": "Licht", "root": "ن و ر", "level": 2},
    {"ar": "ظُلُمَاتٌ", "de": "Finsternisse", "root": "ظ ل م", "level": 2},
    {"ar": "أَجْرٌ", "de": "Lohn", "root": "أ ج ر", "level": 2},
    {"ar": "ذَنْبٌ", "de": "Sünde", "root": "ذ ن ب", "level": 2},
    {"ar": "صَلَاةٌ", "de": "Gebet", "root": "ص ل و", "level": 2},
    {"ar": "زَكَاةٌ", "de": "Abgabe, Zakat", "root": "ز ك و", "level": 2},
    {"ar": "صَبْرٌ", "de": "Geduld", "root": "ص ب ر", "level": 2},
    {"ar": "هُدًى", "de": "Rechtleitung", "root": "ه د ي", "level": 2},
    {"ar": "مَلَكٌ", "de": "Engel", "root": "م ل ك", "level": 2},
    {"ar": "شَيْطَانٌ", "de": "Satan, Teufel", "root": "ش ط ن", "level": 2, "freq": 88},
    {"ar": "نَبِيٌّ", "de": "Prophet", "root": "ن ب أ", "level": 2},
    {"ar": "سَاعَةٌ", "de": "Stunde; die Stunde (Weltende)", "root": "س و ع", "level": 2},
    {"ar": "مَكَانٌ", "de": "Ort", "root": "ك و ن", "level": 2},
    {"ar": "أَوَّلُ", "de": "erster", "root": "أ و ل", "level": 2},
    {"ar": "آخِرُ", "de": "letzter", "root": "أ خ ر", "level": 2},
    {"ar": "صَدْرٌ", "de": "Brust", "root": "ص د ر", "level": 2},
    {"ar": "رُوحٌ", "de": "Geist, Seele", "root": "ر و ح", "level": 2},
    {"ar": "أُمَّةٌ", "de": "Gemeinschaft, Volk", "root": "أ م م", "level": 2},
    {"ar": "رِزْقٌ", "de": "Versorgung", "root": "ر ز ق", "level": 2},
    {"ar": "مُلْكٌ", "de": "Herrschaft, Königtum", "root": "م ل ك", "level": 2},
    {"ar": "عَرْشٌ", "de": "Thron", "root": "ع ر ش", "level": 2},
    {"ar": "حِسَابٌ", "de": "Abrechnung", "root": "ح س ب", "level": 2},
    {"ar": "مِيزَانٌ", "de": "Waage", "root": "و ز ن", "level": 2},
    {"ar": "أَثَرٌ", "de": "Spur", "root": "أ ث ر", "level": 2},
    {"ar": "بَابٌ", "de": "Tür, Tor", "root": "ب و ب", "level": 2},

    # ================= Stufe 3: die haeufigsten Verben =====================
    {"ar": "قَالَ", "de": "sagen", "root": "ق و ل", "level": 3, "freq": 1722},
    {"ar": "كَانَ", "de": "sein", "root": "ك و ن", "level": 3, "freq": 1361},
    {"ar": "آمَنَ", "de": "glauben", "root": "أ م ن", "level": 3},
    {"ar": "كَفَرَ", "de": "nicht glauben, leugnen", "root": "ك ف ر", "level": 3},
    {"ar": "عَلِمَ", "de": "wissen", "root": "ع ل م", "level": 3},
    {"ar": "عَمِلَ", "de": "tun, handeln", "root": "ع م ل", "level": 3},
    {"ar": "جَعَلَ", "de": "machen, setzen", "root": "ج ع ل", "level": 3},
    {"ar": "خَلَقَ", "de": "erschaffen", "root": "خ ل ق", "level": 3},
    {"ar": "أَنْزَلَ", "de": "herabsenden", "root": "ن ز ل", "level": 3},
    {"ar": "جَاءَ", "de": "kommen", "root": "ج ي أ", "level": 3},
    {"ar": "أَتَىٰ", "de": "kommen, bringen", "root": "أ ت ي", "level": 3},
    {"ar": "ذَهَبَ", "de": "gehen, fortgehen", "root": "ذ ه ب", "level": 3},
    {"ar": "رَجَعَ", "de": "zurückkehren", "root": "ر ج ع", "level": 3},
    {"ar": "دَخَلَ", "de": "eintreten", "root": "د خ ل", "level": 3},
    {"ar": "خَرَجَ", "de": "hinausgehen", "root": "خ ر ج", "level": 3},
    {"ar": "أَخَذَ", "de": "nehmen, ergreifen", "root": "أ خ ذ", "level": 3},
    {"ar": "أَعْطَىٰ", "de": "geben", "root": "ع ط و", "level": 3},
    {"ar": "رَأَىٰ", "de": "sehen", "root": "ر أ ي", "level": 3},
    {"ar": "نَظَرَ", "de": "schauen, blicken", "root": "ن ظ ر", "level": 3},
    {"ar": "سَمِعَ", "de": "hören", "root": "س م ع", "level": 3},
    {"ar": "فَعَلَ", "de": "tun", "root": "ف ع ل", "level": 3},
    {"ar": "أَرَادَ", "de": "wollen", "root": "ر و د", "level": 3},
    {"ar": "اسْتَطَاعَ", "de": "können, vermögen", "root": "ط و ع", "level": 3},
    {"ar": "وَجَدَ", "de": "finden", "root": "و ج د", "level": 3},
    {"ar": "دَعَا", "de": "rufen, bitten", "root": "د ع و", "level": 3},
    {"ar": "عَبَدَ", "de": "dienen, anbeten", "root": "ع ب د", "level": 3},
    {"ar": "سَجَدَ", "de": "sich niederwerfen", "root": "س ج د", "level": 3},
    {"ar": "صَلَّىٰ", "de": "beten", "root": "ص ل و", "level": 3},
    {"ar": "تَابَ", "de": "Reue zeigen; Reue annehmen", "root": "ت و ب", "level": 3},
    {"ar": "غَفَرَ", "de": "vergeben", "root": "غ ف ر", "level": 3},
    {"ar": "رَحِمَ", "de": "sich erbarmen", "root": "ر ح م", "level": 3},
    {"ar": "هَدَىٰ", "de": "rechtleiten", "root": "ه د ي", "level": 3},
    {"ar": "أَضَلَّ", "de": "in die Irre führen", "root": "ض ل ل", "level": 3},
    {"ar": "ضَلَّ", "de": "irregehen", "root": "ض ل ل", "level": 3},
    {"ar": "نَصَرَ", "de": "helfen, beistehen", "root": "ن ص ر", "level": 3},
    {"ar": "أَمَرَ", "de": "befehlen", "root": "أ م ر", "level": 3},
    {"ar": "نَهَىٰ", "de": "verbieten", "root": "ن ه ي", "level": 3},
    {"ar": "حَكَمَ", "de": "richten, urteilen", "root": "ح ك م", "level": 3},
    {"ar": "كَتَبَ", "de": "schreiben; vorschreiben", "root": "ك ت ب", "level": 3},
    {"ar": "قَرَأَ", "de": "lesen, vortragen", "root": "ق ر أ", "level": 3},
    {"ar": "ذَكَرَ", "de": "gedenken, erwähnen", "root": "ذ ك ر", "level": 3},
    {"ar": "نَسِيَ", "de": "vergessen", "root": "ن س ي", "level": 3},
    {"ar": "عَقَلَ", "de": "begreifen, verstehen", "root": "ع ق ل", "level": 3},
    {"ar": "فَقِهَ", "de": "verstehen, begreifen", "root": "ف ق ه", "level": 3},
    {"ar": "خَافَ", "de": "fürchten", "root": "خ و ف", "level": 3},
    {"ar": "أَحَبَّ", "de": "lieben", "root": "ح ب ب", "level": 3},
    {"ar": "كَرِهَ", "de": "verabscheuen", "root": "ك ر ه", "level": 3},
    {"ar": "مَاتَ", "de": "sterben", "root": "م و ت", "level": 3},
    {"ar": "أَحْيَا", "de": "lebendig machen", "root": "ح ي ي", "level": 3},
    {"ar": "بَعَثَ", "de": "auferwecken, entsenden", "root": "ب ع ث", "level": 3},
    {"ar": "حَشَرَ", "de": "versammeln", "root": "ح ش ر", "level": 3},
    {"ar": "أَكَلَ", "de": "essen", "root": "أ ك ل", "level": 3},
    {"ar": "شَرِبَ", "de": "trinken", "root": "ش ر ب", "level": 3},
    {"ar": "قَامَ", "de": "aufstehen, sich erheben", "root": "ق و م", "level": 3},
    {"ar": "فَتَحَ", "de": "öffnen", "root": "ف ت ح", "level": 3},
    {"ar": "مَلَكَ", "de": "besitzen, beherrschen", "root": "م ل ك", "level": 3},
    {"ar": "أَنْفَقَ", "de": "ausgeben, spenden", "root": "ن ف ق", "level": 3},
    {"ar": "كَسَبَ", "de": "erwerben", "root": "ك س ب", "level": 3},
    {"ar": "ظَلَمَ", "de": "Unrecht tun", "root": "ظ ل م", "level": 3},
    {"ar": "أَصْلَحَ", "de": "in Ordnung bringen", "root": "ص ل ح", "level": 3},
    {"ar": "أَفْسَدَ", "de": "verderben, Unheil stiften", "root": "ف س د", "level": 3},
    {"ar": "شَكَرَ", "de": "danken", "root": "ش ك ر", "level": 3},
    {"ar": "صَبَرَ", "de": "geduldig sein", "root": "ص ب ر", "level": 3},
    {"ar": "اتَّقَىٰ", "de": "gottesfürchtig sein", "root": "و ق ي", "level": 3},
    {"ar": "أَسْلَمَ", "de": "sich hingeben, Muslim werden", "root": "س ل م", "level": 3},
    {"ar": "شَهِدَ", "de": "bezeugen", "root": "ش ه د", "level": 3},
    {"ar": "سَبَّحَ", "de": "lobpreisen", "root": "س ب ح", "level": 3},
    {"ar": "حَمِدَ", "de": "loben", "root": "ح م د", "level": 3},
    {"ar": "اسْتَغْفَرَ", "de": "um Vergebung bitten", "root": "غ ف ر", "level": 3},
    {"ar": "أَعُوذُ", "de": "ich nehme Zuflucht", "root": "ع و ذ", "level": 3},

    # ================= Stufe 4: Eigenschaften und Gottesnamen ==============
    {"ar": "الرَّحْمَٰنُ", "de": "der Allerbarmer", "root": "ر ح م", "level": 4},
    {"ar": "الرَّحِيمُ", "de": "der Barmherzige", "root": "ر ح م", "level": 4},
    {"ar": "عَزِيزٌ", "de": "mächtig, erhaben", "root": "ع ز ز", "level": 4},
    {"ar": "حَكِيمٌ", "de": "weise", "root": "ح ك م", "level": 4},
    {"ar": "عَلِيمٌ", "de": "allwissend", "root": "ع ل م", "level": 4},
    {"ar": "قَدِيرٌ", "de": "allmächtig", "root": "ق د ر", "level": 4},
    {"ar": "غَفُورٌ", "de": "vergebend", "root": "غ ف ر", "level": 4},
    {"ar": "سَمِيعٌ", "de": "allhörend", "root": "س م ع", "level": 4},
    {"ar": "بَصِيرٌ", "de": "allsehend", "root": "ب ص ر", "level": 4},
    {"ar": "عَظِيمٌ", "de": "gewaltig", "root": "ع ظ م", "level": 4},
    {"ar": "كَرِيمٌ", "de": "edelmütig, großzügig", "root": "ك ر م", "level": 4},
    {"ar": "خَبِيرٌ", "de": "kundig", "root": "خ ب ر", "level": 4},
    {"ar": "حَلِيمٌ", "de": "nachsichtig", "root": "ح ل م", "level": 4},
    {"ar": "شَكُورٌ", "de": "dankbar anerkennend", "root": "ش ك ر", "level": 4},
    {"ar": "حَيٌّ", "de": "lebendig", "root": "ح ي ي", "level": 4},
    {"ar": "قَيُّومٌ", "de": "beständig, alles erhaltend", "root": "ق و م", "level": 4},
    {"ar": "أَحَدٌ", "de": "ein Einziger", "root": "أ ح د", "level": 4},
    {"ar": "وَاحِدٌ", "de": "einer, einzig", "root": "و ح د", "level": 4},
    {"ar": "صَمَدٌ", "de": "der Absolute", "root": "ص م د", "level": 4},
    {"ar": "مَلِكٌ", "de": "König", "root": "م ل ك", "level": 4},
    {"ar": "خَالِقٌ", "de": "Schöpfer", "root": "خ ل ق", "level": 4},
    {"ar": "تَوَّابٌ", "de": "Reue-Annehmend", "root": "ت و ب", "level": 4},
    {"ar": "مُؤْمِنٌ", "de": "Gläubiger", "root": "أ م ن", "level": 4},
    {"ar": "كَافِرٌ", "de": "Ungläubiger", "root": "ك ف ر", "level": 4},
    {"ar": "مُسْلِمٌ", "de": "Muslim, Gottergebener", "root": "س ل م", "level": 4},
    {"ar": "مُنَافِقٌ", "de": "Heuchler", "root": "ن ف ق", "level": 4},
    {"ar": "ظَالِمٌ", "de": "Ungerechter", "root": "ظ ل م", "level": 4},
    {"ar": "صَالِحٌ", "de": "rechtschaffen", "root": "ص ل ح", "level": 4},
    {"ar": "صَادِقٌ", "de": "wahrhaftig", "root": "ص د ق", "level": 4},
    {"ar": "كَاذِبٌ", "de": "lügnerisch", "root": "ك ذ ب", "level": 4},
    {"ar": "مُتَّقٍ", "de": "gottesfürchtig", "root": "و ق ي", "level": 4},
    {"ar": "طَيِّبٌ", "de": "gut, rein", "root": "ط ي ب", "level": 4},
    {"ar": "خَبِيثٌ", "de": "schlecht, unrein", "root": "خ ب ث", "level": 4},
    {"ar": "كَثِيرٌ", "de": "viel", "root": "ك ث ر", "level": 4},
    {"ar": "قَلِيلٌ", "de": "wenig", "root": "ق ل ل", "level": 4},
    {"ar": "شَدِيدٌ", "de": "heftig, streng", "root": "ش د د", "level": 4},
    {"ar": "قَرِيبٌ", "de": "nah", "root": "ق ر ب", "level": 4},
    {"ar": "بَعِيدٌ", "de": "fern", "root": "ب ع د", "level": 4},
    {"ar": "كَبِيرٌ", "de": "groß", "root": "ك ب ر", "level": 4},
    {"ar": "مُبِينٌ", "de": "deutlich, klar", "root": "ب ي ن", "level": 4},
    {"ar": "مُسْتَقِيمٌ", "de": "gerade (Weg)", "root": "ق و م", "level": 4},
    {"ar": "عَالَمِينَ", "de": "die Welten, Geschöpfe", "root": "ع ل م", "level": 4},
    {"ar": "غَيْبٌ", "de": "das Verborgene", "root": "غ ي ب", "level": 4},
    {"ar": "بَرَكَةٌ", "de": "Segen", "root": "ب ر ك", "level": 4},
    {"ar": "سَلَامٌ", "de": "Friede", "root": "س ل م", "level": 4},
    {"ar": "فَضْلٌ", "de": "Huld, Gunst", "root": "ف ض ل", "level": 4},
    {"ar": "نِعْمَةٌ", "de": "Gnade, Wohltat", "root": "ن ع م", "level": 4},
    {"ar": "تَقْوَىٰ", "de": "Gottesfurcht", "root": "و ق ي", "level": 4},
    {"ar": "شُكْرٌ", "de": "Dankbarkeit", "root": "ش ك ر", "level": 4},
    {"ar": "ذِكْرٌ", "de": "Gedenken; Ermahnung", "root": "ذ ك ر", "level": 4},
    {"ar": "قُرْآنٌ", "de": "Qurʾān, Lesung", "root": "ق ر أ", "level": 4},
    {"ar": "فُرْقَانٌ", "de": "Unterscheidung", "root": "ف ر ق", "level": 4},
    {"ar": "صِرَاطٌ", "de": "Weg, Pfad", "root": "ص ر ط", "level": 4},
    {"ar": "أُجُورٌ", "de": "Löhne", "root": "أ ج ر", "level": 4},
    {"ar": "خَلْقٌ", "de": "Schöpfung", "root": "خ ل ق", "level": 4},

    # ================= Stufe 5: aus den Gebetstexten =======================
    # Diese Woerter kommen im Quran insgesamt selten vor, stehen aber in den
    # Texten, die taeglich gebetet werden. Eine reine Haeufigkeitsliste wuerde
    # sie nie erfassen - deshalb der zweite Strang.
    # Bedeutung hier als Grundbedeutung, nicht als Uebersetzung der Versstelle.
    {"ar": "مَالِكٌ", "de": "Herrscher, Besitzer", "root": "م ل ك", "level": 5},
    {"ar": "اسْتَعَانَ", "de": "um Hilfe bitten", "root": "ع و ن", "level": 5},
    {"ar": "أَنْعَمَ", "de": "Gnade erweisen", "root": "ن ع م", "level": 5},
    {"ar": "غَضِبَ", "de": "zürnen, zornig sein", "root": "غ ض ب", "level": 5},
    {"ar": "كُفُؤٌ", "de": "ebenbürtig, gleich", "root": "ك ف أ", "level": 5},
    {"ar": "فَلَقٌ", "de": "Frühlicht, Tagesanbruch", "root": "ف ل ق", "level": 5},
    {"ar": "غَاسِقٌ", "de": "hereinbrechende Dunkelheit", "root": "غ س ق", "level": 5},
    {"ar": "وَقَبَ", "de": "hereinbrechen (Dunkelheit)", "root": "و ق ب", "level": 5},
    {"ar": "نَفَّاثَةٌ", "de": "Anblaserin (in Knoten)", "root": "ن ف ث", "level": 5},
    {"ar": "عُقْدَةٌ", "de": "Knoten", "root": "ع ق د", "level": 5},
    {"ar": "حَاسِدٌ", "de": "Neider", "root": "ح س د", "level": 5},
    {"ar": "حَسَدَ", "de": "beneiden", "root": "ح س د", "level": 5},
    {"ar": "إِلَٰهٌ", "de": "Gott, Gottheit", "root": "أ ل ه", "level": 5},
    {"ar": "وَسْوَاسٌ", "de": "Einflüsterer", "root": "و س و س", "level": 5},
    {"ar": "خَنَّاسٌ", "de": "der sich Zurückziehende", "root": "خ ن س", "level": 5},
    {"ar": "وَسْوَسَ", "de": "einflüstern", "root": "و س و س", "level": 5},
    {"ar": "إِنْسَانٌ", "de": "Mensch", "root": "أ ن س", "level": 5},
    {"ar": "خُسْرٌ", "de": "Verlust", "root": "خ س ر", "level": 5},
    {"ar": "صَالِحَةٌ", "de": "gute Tat (weibl. Form von صَالِح)", "root": "ص ل ح", "level": 5},
    {"ar": "تَوَاصَىٰ", "de": "einander nahelegen, sich gegenseitig ermahnen", "root": "و ص ي", "level": 5},
    {"ar": "كَوْثَرٌ", "de": "Fülle (Fluss im Paradies)", "root": "ك ث ر", "level": 5},
    {"ar": "نَحَرَ", "de": "opfern (Opfertier schlachten)", "root": "ن ح ر", "level": 5},
    {"ar": "شَانِئٌ", "de": "Hasser, Feind", "root": "ش ن أ", "level": 5},
    {"ar": "أَبْتَرُ", "de": "ohne Nachkommen, abgeschnitten", "root": "ب ت ر", "level": 5},
    {"ar": "فَوْجٌ", "de": "Schar, Gruppe", "root": "ف و ج", "level": 5},
    {"ar": "تَحِيَّةٌ", "de": "Gruß", "root": "ح ي ي", "level": 5},
    {"ar": "طَيِّبَةٌ", "de": "gute Sache (weibl. Form von طَيِّب)", "root": "ط ي ب", "level": 5},
    {"ar": "سُبْحَانَ", "de": "Preis sei (Lobpreisung)", "root": "س ب ح", "level": 5},
    {"ar": "أَعْلَىٰ", "de": "der Höchste", "root": "ع ل و", "level": 5},
    {"ar": "عَصْرٌ", "de": "Zeit; Nachmittag", "root": "ع ص ر", "level": 5},
    {"ar": "جِنَّةٌ", "de": "Dschinn (Gesamtheit)", "root": "ج ن ن", "level": 5},
    {"ar": "عَابِدٌ", "de": "Diener, Anbetender", "root": "ع ب د", "level": 5},
    {"ar": "لَيْلَةٌ", "de": "Nacht (eine einzelne)", "root": "ل ي ل", "level": 5},
    {"ar": "أَدْرَىٰ", "de": "wissen lassen, kundtun", "root": "د ر ي", "level": 5},
    {"ar": "أَلْفٌ", "de": "tausend", "root": "أ ل ف", "level": 5},
    {"ar": "تَنَزَّلَ", "de": "herabkommen", "root": "ن ز ل", "level": 5},
    {"ar": "إِذْنٌ", "de": "Erlaubnis", "root": "أ ذ ن", "level": 5},
    {"ar": "مَطْلَعٌ", "de": "Aufgang, Anbruch", "root": "ط ل ع", "level": 5},
    {"ar": "قَدْرٌ", "de": "Bestimmung, Maß", "root": "ق د ر", "level": 5},
    {"ar": "فَجْرٌ", "de": "Morgendämmerung", "root": "ف ج ر", "level": 5},
    {"ar": "إِيلَافٌ", "de": "Vertrautheit, Gewöhnung", "root": "أ ل ف", "level": 5},
    {"ar": "شِتَاءٌ", "de": "Winter", "root": "ش ت و", "level": 5},
    {"ar": "صَيْفٌ", "de": "Sommer", "root": "ص ي ف", "level": 5},
    {"ar": "رِحْلَةٌ", "de": "Reise", "root": "ر ح ل", "level": 5},
    {"ar": "أَطْعَمَ", "de": "speisen, zu essen geben", "root": "ط ع م", "level": 5},
    {"ar": "جُوعٌ", "de": "Hunger", "root": "ج و ع", "level": 5},
    {"ar": "خَوْفٌ", "de": "Furcht, Angst", "root": "خ و ف", "level": 5},
    {"ar": "صَاحِبٌ", "de": "Gefährte, Begleiter", "root": "ص ح ب", "level": 5},
    {"ar": "فِيلٌ", "de": "Elefant", "root": "ف ي ل", "level": 5},
    {"ar": "كَيْدٌ", "de": "List, Ränke", "root": "ك ي د", "level": 5},
    {"ar": "تَضْلِيلٌ", "de": "Irreführung, Fehlschlag", "root": "ض ل ل", "level": 5},
    {"ar": "طَيْرٌ", "de": "Vogel, Vögel", "root": "ط ي ر", "level": 5},
    {"ar": "أَبَابِيلُ", "de": "Schwärme, Scharen", "root": "أ ب ل", "level": 5},
    {"ar": "حَجَرٌ", "de": "Stein", "root": "ح ج ر", "level": 5},
    {"ar": "سِجِّيلٌ", "de": "gebrannter Lehm", "root": "س ج ل", "level": 5},
    {"ar": "عَصْفٌ", "de": "Halme, Spreu", "root": "ع ص ف", "level": 5},
    {"ar": "مَأْكُولٌ", "de": "abgefressen, gegessen", "root": "أ ك ل", "level": 5},
]
