# -*- coding: utf-8 -*-
"""
vocab_extra.py
Erweiterung des Alltagswortschatzes ueber das Lehrbuch hinaus.

Aufbau eines Eintrags:
    cat   Kategorie (neue oder bestehende)
    de    deutsche Bedeutung
    ar    Fusha, voll vokalisiert
    type  noun | verb | adjective | number | phrase
    pl    Plural            (nur noun, None wenn keiner gebraeuchlich)
    g     Genus m|f         (nur noun)
    fem   weibliche Form    (nur adjective, wenn die Regel nicht greift;
                             fem=None heisst: das Wort hat keine eigene
                             weibliche Form)
    pres  Praesens          (nur verb - der Stammvokal ist nicht ableitbar)
    prep  verlangte Praeposition (optional)
    note  kurzer Hinweis auf der Karte (optional)

Sprechform, Zukunft und Befehlsform werden beim Bauen automatisch ergaenzt.
"""

EXTRA = [
    # ================= Zahlen =================
    # Hinweis zur Kongruenz steht bei 3: bei maennlichen Gezaehlten nimmt man
    # die Form MIT ة - das ist die sogenannte umgekehrte Uebereinstimmung.
    {"cat": "Zahlen", "type": "number", "de": "null", "ar": "صِفْرٌ"},
    {"cat": "Zahlen", "type": "number", "de": "zwei", "ar": "اِثْنَانِ"},
    {"cat": "Zahlen", "type": "number", "de": "drei", "ar": "ثَلَاثَةٌ",
     "note": "Bei männlichen Dingen mit ة: ثَلَاثَةُ كُتُبٍ (drei Bücher)"},
    {"cat": "Zahlen", "type": "number", "de": "vier", "ar": "أَرْبَعَةٌ"},
    {"cat": "Zahlen", "type": "number", "de": "fünf", "ar": "خَمْسَةٌ"},
    {"cat": "Zahlen", "type": "number", "de": "sechs", "ar": "سِتَّةٌ"},
    {"cat": "Zahlen", "type": "number", "de": "sieben", "ar": "سَبْعَةٌ"},
    {"cat": "Zahlen", "type": "number", "de": "acht", "ar": "ثَمَانِيَةٌ"},
    {"cat": "Zahlen", "type": "number", "de": "neun", "ar": "تِسْعَةٌ"},
    {"cat": "Zahlen", "type": "number", "de": "zehn", "ar": "عَشَرَةٌ"},
    {"cat": "Zahlen", "type": "number", "de": "elf", "ar": "أَحَدَ عَشَرَ"},
    {"cat": "Zahlen", "type": "number", "de": "zwölf", "ar": "اِثْنَا عَشَرَ"},
    {"cat": "Zahlen", "type": "number", "de": "dreizehn", "ar": "ثَلَاثَةَ عَشَرَ"},
    {"cat": "Zahlen", "type": "number", "de": "zwanzig", "ar": "عِشْرُونَ"},
    {"cat": "Zahlen", "type": "number", "de": "dreißig", "ar": "ثَلَاثُونَ"},
    {"cat": "Zahlen", "type": "number", "de": "vierzig", "ar": "أَرْبَعُونَ"},
    {"cat": "Zahlen", "type": "number", "de": "fünfzig", "ar": "خَمْسُونَ"},
    {"cat": "Zahlen", "type": "number", "de": "sechzig", "ar": "سِتُّونَ"},
    {"cat": "Zahlen", "type": "number", "de": "siebzig", "ar": "سَبْعُونَ"},
    {"cat": "Zahlen", "type": "number", "de": "achtzig", "ar": "ثَمَانُونَ"},
    {"cat": "Zahlen", "type": "number", "de": "neunzig", "ar": "تِسْعُونَ"},
    {"cat": "Zahlen", "type": "number", "de": "hundert", "ar": "مِائَةٌ"},
    {"cat": "Zahlen", "type": "number", "de": "tausend", "ar": "أَلْفٌ"},
    {"cat": "Zahlen", "type": "number", "de": "eine Million", "ar": "مِلْيُونٌ"},
    {"cat": "Zahlen", "type": "number", "de": "zweiter", "ar": "ثَانٍ"},
    {"cat": "Zahlen", "type": "number", "de": "dritter", "ar": "ثَالِثٌ"},
    {"cat": "Zahlen", "type": "number", "de": "die Hälfte", "ar": "نِصْفٌ"},
    {"cat": "Zahlen", "type": "number", "de": "ein Viertel", "ar": "رُبْعٌ"},

    # ================= Farben =================
    # Grundfarben folgen dem Muster أَفْعَلُ / فَعْلَاءُ – die weibliche Form
    # ist NICHT mit ة gebildet, deshalb steht sie hier ausdrücklich.
    {"cat": "Farben", "type": "adjective", "de": "rot", "ar": "أَحْمَرُ", "fem": "حَمْرَاءُ"},
    {"cat": "Farben", "type": "adjective", "de": "blau", "ar": "أَزْرَقُ", "fem": "زَرْقَاءُ"},
    {"cat": "Farben", "type": "adjective", "de": "grün", "ar": "أَخْضَرُ", "fem": "خَضْرَاءُ"},
    {"cat": "Farben", "type": "adjective", "de": "gelb", "ar": "أَصْفَرُ", "fem": "صَفْرَاءُ"},
    {"cat": "Farben", "type": "adjective", "de": "schwarz", "ar": "أَسْوَدُ", "fem": "سَوْدَاءُ"},
    {"cat": "Farben", "type": "adjective", "de": "weiß", "ar": "أَبْيَضُ", "fem": "بَيْضَاءُ"},
    {"cat": "Farben", "type": "adjective", "de": "braun", "ar": "بُنِّيٌّ"},
    {"cat": "Farben", "type": "adjective", "de": "grau", "ar": "رَمَادِيٌّ"},
    {"cat": "Farben", "type": "adjective", "de": "orange", "ar": "بُرْتُقَالِيٌّ"},
    {"cat": "Farben", "type": "adjective", "de": "rosa", "ar": "وَرْدِيٌّ"},
    {"cat": "Farben", "type": "adjective", "de": "lila", "ar": "بَنَفْسَجِيٌّ"},
    {"cat": "Farben", "type": "adjective", "de": "golden", "ar": "ذَهَبِيٌّ"},
    {"cat": "Farben", "type": "adjective", "de": "silbern", "ar": "فِضِّيٌّ"},
    {"cat": "Farben", "type": "adjective", "de": "hell", "ar": "فَاتِحٌ"},
    {"cat": "Farben", "type": "adjective", "de": "dunkel", "ar": "دَاكِنٌ"},

    # ================= Zeit und Kalender =================
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Montag", "ar": "اَلْإِثْنَيْنِ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Dienstag", "ar": "اَلثُّلَاثَاءُ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Mittwoch", "ar": "اَلْأَرْبِعَاءُ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Donnerstag", "ar": "اَلْخَمِيسُ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Freitag", "ar": "اَلْجُمُعَةُ", "pl": None, "g": "f"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Samstag", "ar": "اَلسَّبْتُ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Sonntag", "ar": "اَلْأَحَدُ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "phrase", "de": "heute", "ar": "اَلْيَوْمَ"},
    {"cat": "Zeit und Kalender", "type": "phrase", "de": "morgen", "ar": "غَدًا"},
    {"cat": "Zeit und Kalender", "type": "phrase", "de": "gestern", "ar": "أَمْسِ"},
    {"cat": "Zeit und Kalender", "type": "phrase", "de": "später", "ar": "لَاحِقًا"},
    {"cat": "Zeit und Kalender", "type": "phrase", "de": "immer", "ar": "دَائِمًا"},
    {"cat": "Zeit und Kalender", "type": "phrase", "de": "nie", "ar": "أَبَدًا"},
    {"cat": "Zeit und Kalender", "type": "phrase", "de": "manchmal", "ar": "أَحْيَانًا"},
    {"cat": "Zeit und Kalender", "type": "phrase", "de": "oft", "ar": "كَثِيرًا"},
    {"cat": "Zeit und Kalender", "type": "phrase", "de": "selten", "ar": "نَادِرًا"},
    {"cat": "Zeit und Kalender", "type": "phrase", "de": "sofort", "ar": "حَالًا"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Frühling", "ar": "رَبِيعٌ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Sommer", "ar": "صَيْفٌ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Herbst", "ar": "خَرِيفٌ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Winter", "ar": "شِتَاءٌ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Morgen (Tageszeit)", "ar": "صَبَاحٌ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Abend", "ar": "مَسَاءٌ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Mitternacht", "ar": "مُنْتَصَفُ اللَّيْلِ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Termin, Verabredung", "ar": "مَوْعِدٌ", "pl": "مَوَاعِيدُ", "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Feiertag, Fest", "ar": "عِيدٌ", "pl": "أَعْيَادٌ", "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Geburtstag", "ar": "عِيدُ مِيلَادٍ", "pl": None, "g": "m"},
    {"cat": "Zeit und Kalender", "type": "noun", "de": "Ferien, Urlaub", "ar": "عُطْلَةٌ", "pl": "عُطَلٌ", "g": "f"},

    # ================= Kleidung =================
    {"cat": "Kleidung", "type": "noun", "de": "Hemd", "ar": "قَمِيصٌ", "pl": "قُمْصَانٌ", "g": "m"},
    {"cat": "Kleidung", "type": "noun", "de": "Hose", "ar": "بَنْطَلُونٌ", "pl": "بَنْطَلُونَاتٌ", "g": "m"},
    {"cat": "Kleidung", "type": "noun", "de": "Schuh", "ar": "حِذَاءٌ", "pl": "أَحْذِيَةٌ", "g": "m"},
    {"cat": "Kleidung", "type": "noun", "de": "Jacke", "ar": "سُتْرَةٌ", "pl": "سُتَرٌ", "g": "f"},
    {"cat": "Kleidung", "type": "noun", "de": "Mantel", "ar": "مِعْطَفٌ", "pl": "مَعَاطِفُ", "g": "m"},
    {"cat": "Kleidung", "type": "noun", "de": "Socke", "ar": "جَوْرَبٌ", "pl": "جَوَارِبُ", "g": "m"},
    {"cat": "Kleidung", "type": "noun", "de": "Mütze, Kappe", "ar": "قُبَّعَةٌ", "pl": "قُبَّعَاتٌ", "g": "f"},
    {"cat": "Kleidung", "type": "noun", "de": "Kopftuch", "ar": "حِجَابٌ", "pl": "أَحْجِبَةٌ", "g": "m"},
    {"cat": "Kleidung", "type": "noun", "de": "Gürtel", "ar": "حِزَامٌ", "pl": "أَحْزِمَةٌ", "g": "m"},
    {"cat": "Kleidung", "type": "noun", "de": "Ring", "ar": "خَاتَمٌ", "pl": "خَوَاتِمُ", "g": "m"},
    {"cat": "Kleidung", "type": "noun", "de": "Brille", "ar": "نَظَّارَةٌ", "pl": "نَظَّارَاتٌ", "g": "f"},
    {"cat": "Kleidung", "type": "noun", "de": "Kleidung (allgemein)", "ar": "مَلَابِسُ", "pl": None, "g": "f"},
    {"cat": "Kleidung", "type": "noun", "de": "Schal, Tuch", "ar": "وِشَاحٌ", "pl": "أَوْشِحَةٌ", "g": "m"},
    {"cat": "Kleidung", "type": "noun", "de": "Größe (Kleidung)", "ar": "مَقَاسٌ", "pl": "مَقَاسَاتٌ", "g": "m"},

    # ================= Berufe =================
    {"cat": "Berufe", "type": "noun", "de": "Bäcker", "ar": "خَبَّازٌ", "pl": "خَبَّازُونَ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Koch", "ar": "طَبَّاخٌ", "pl": "طَبَّاخُونَ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Fahrer", "ar": "سَائِقٌ", "pl": "سَائِقُونَ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Verkäufer", "ar": "بَائِعٌ", "pl": "بَاعَةٌ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Polizist", "ar": "شُرْطِيٌّ", "pl": "شُرْطَةٌ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Schneider", "ar": "خَيَّاطٌ", "pl": "خَيَّاطُونَ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Friseur", "ar": "حَلَّاقٌ", "pl": "حَلَّاقُونَ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Anwalt", "ar": "مُحَامٍ", "pl": "مُحَامُونَ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Richter", "ar": "قَاضٍ", "pl": "قُضَاةٌ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Journalist", "ar": "صَحَفِيٌّ", "pl": "صَحَفِيُّونَ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Arbeiter", "ar": "عَامِلٌ", "pl": "عُمَّالٌ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Apotheker", "ar": "صَيْدَلِيٌّ", "pl": "صَيَادِلَةٌ", "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Zahnarzt", "ar": "طَبِيبُ أَسْنَانٍ", "pl": None, "g": "m"},
    {"cat": "Berufe", "type": "noun", "de": "Beruf", "ar": "مِهْنَةٌ", "pl": "مِهَنٌ", "g": "f"},

    # ================= Familie (Ergänzung) =================
    {"cat": "Familie und Menschen", "type": "noun", "de": "Familie", "ar": "عَائِلَةٌ", "pl": "عَائِلَاتٌ", "g": "f"},
    {"cat": "Familie und Menschen", "type": "noun", "de": "Enkel", "ar": "حَفِيدٌ", "pl": "أَحْفَادٌ", "g": "m"},
    {"cat": "Familie und Menschen", "type": "noun", "de": "Enkelin", "ar": "حَفِيدَةٌ", "pl": "حَفِيدَاتٌ", "g": "f"},
    {"cat": "Familie und Menschen", "type": "noun", "de": "Cousin (Sohn des Onkels)", "ar": "اِبْنُ الْعَمِّ", "pl": None, "g": "m"},
    {"cat": "Familie und Menschen", "type": "noun", "de": "Schwiegervater", "ar": "حَمٌ", "pl": "أَحْمَاءٌ", "g": "m"},
    {"cat": "Familie und Menschen", "type": "noun", "de": "Schwiegermutter", "ar": "حَمَاةٌ", "pl": "حَمَوَاتٌ", "g": "f"},
    {"cat": "Familie und Menschen", "type": "noun", "de": "Bräutigam", "ar": "عَرِيسٌ", "pl": "عِرْسَانٌ", "g": "m"},
    {"cat": "Familie und Menschen", "type": "noun", "de": "Braut", "ar": "عَرُوسٌ", "pl": "عَرَائِسُ", "g": "f"},
    {"cat": "Familie und Menschen", "type": "noun", "de": "Säugling, Baby", "ar": "رَضِيعٌ", "pl": "رُضَّعٌ", "g": "m"},
    {"cat": "Familie und Menschen", "type": "noun", "de": "Hochzeit", "ar": "زَوَاجٌ", "pl": None, "g": "m"},
    {"cat": "Familie und Menschen", "type": "noun", "de": "Waise", "ar": "يَتِيمٌ", "pl": "أَيْتَامٌ", "g": "m"},

    # ================= Höflichkeit und Gespräch =================
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "bitte (Aufforderung)", "ar": "مِنْ فَضْلِكَ",
     "note": "zu einer Frau: مِنْ فَضْلِكِ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "danke", "ar": "شُكْرًا"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "vielen Dank", "ar": "شُكْرًا جَزِيلًا"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "gern geschehen", "ar": "عَفْوًا"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Entschuldigung", "ar": "آسِفٌ",
     "note": "eine Frau sagt: آسِفَةٌ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "kein Problem", "ar": "لَا مُشْكِلَةَ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "ja", "ar": "نَعَمْ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "nein", "ar": "لَا"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "vielleicht", "ar": "رُبَّمَا"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "natürlich, klar", "ar": "طَبْعًا"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "einverstanden", "ar": "مُوَافِقٌ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Wie geht es dir?", "ar": "كَيْفَ حَالُكَ؟",
     "note": "zu einer Frau: كَيْفَ حَالُكِ؟"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Mir geht es gut", "ar": "أَنَا بِخَيْرٍ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Wie heißt du?", "ar": "مَا اسْمُكَ؟"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Ich heiße …", "ar": "اِسْمِي …"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Woher kommst du?", "ar": "مِنْ أَيْنَ أَنْتَ؟"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Ich verstehe nicht", "ar": "لَا أَفْهَمُ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Sprich bitte langsam", "ar": "تَكَلَّمْ بِبُطْءٍ مِنْ فَضْلِكَ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Was bedeutet das?", "ar": "مَا مَعْنَى ذَٰلِكَ؟"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Wie sagt man …?", "ar": "كَيْفَ نَقُولُ …؟"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Guten Morgen", "ar": "صَبَاحَ الْخَيْرِ",
     "note": "Antwort: صَبَاحَ النُّورِ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Guten Abend", "ar": "مَسَاءَ الْخَيْرِ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Willkommen", "ar": "أَهْلًا وَسَهْلًا"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Auf Wiedersehen", "ar": "مَعَ السَّلَامَةِ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Wie viel kostet das?", "ar": "بِكَمْ هَٰذَا؟"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Wo ist …?", "ar": "أَيْنَ …؟"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Ich möchte …", "ar": "أُرِيدُ …"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Ich brauche …", "ar": "أَحْتَاجُ إِلَى …"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Hilf mir bitte", "ar": "سَاعِدْنِي مِنْ فَضْلِكَ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "so Gott will", "ar": "إِنْ شَاءَ اللَّهُ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Lob sei Allah", "ar": "اَلْحَمْدُ لِلَّهِ"},
    {"cat": "Höflichkeit und Gespräch", "type": "phrase", "de": "Gott segne dich", "ar": "بَارَكَ اللَّهُ فِيكَ"},

    # ================= Verben (Ergänzung) =================
    # Das Präsens steht ausdrücklich dabei: der Stammvokal (يَفْعَلُ / يَفْعِلُ /
    # يَفْعُلُ) ist aus der Vergangenheit nicht ableitbar. Zukunft und
    # Befehlsform entstehen daraus automatisch.
    {"cat": "Verben", "type": "verb", "de": "tun, machen", "ar": "فَعَلَ", "pres": "يَفْعَلُ"},
    {"cat": "Verben", "type": "verb", "de": "anbieten", "ar": "عَرَضَ", "pres": "يَعْرِضُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "sich bemühen", "ar": "اِجْتَهَدَ", "pres": "يَجْتَهِدُ", "prep": "فِي"},
    {"cat": "Verben", "type": "verb", "de": "aufstehen", "ar": "قَامَ", "pres": "يَقُومُ", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "sich beeilen", "ar": "أَسْرَعَ", "pres": "يُسْرِعُ"},
    {"cat": "Verben", "type": "verb", "de": "begleiten", "ar": "رَافَقَ", "pres": "يُرَافِقُ"},
    {"cat": "Verben", "type": "verb", "de": "aufbewahren, behalten", "ar": "اِحْتَفَظَ", "pres": "يَحْتَفِظُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "bekommen, erhalten", "ar": "حَصَلَ", "pres": "يَحْصُلُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "bemerken", "ar": "لَاحَظَ", "pres": "يُلَاحِظُ"},
    {"cat": "Verben", "type": "verb", "de": "mitteilen, informieren", "ar": "أَخْبَرَ", "pres": "يُخْبِرُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "beschreiben", "ar": "وَصَفَ", "pres": "يَصِفُ"},
    {"cat": "Verben", "type": "verb", "de": "besprechen, diskutieren", "ar": "نَاقَشَ", "pres": "يُنَاقِشُ"},
    {"cat": "Verben", "type": "verb", "de": "bestätigen", "ar": "أَكَّدَ", "pres": "يُؤَكِّدُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "bewegen", "ar": "حَرَّكَ", "pres": "يُحَرِّكُ"},
    {"cat": "Verben", "type": "verb", "de": "beweisen", "ar": "أَثْبَتَ", "pres": "يُثْبِتُ"},
    {"cat": "Verben", "type": "verb", "de": "zweifeln", "ar": "شَكَّ", "pres": "يَشُكُّ", "prep": "فِي"},
    {"cat": "Verben", "type": "verb", "de": "bringen", "ar": "أَحْضَرَ", "pres": "يُحْضِرُ"},
    {"cat": "Verben", "type": "verb", "de": "danken", "ar": "شَكَرَ", "pres": "يَشْكُرُ", "prep": "عَلَى",
     "note": "شَكَرَهُ عَلَى – die Person steht ohne Vorwort"},
    {"cat": "Verben", "type": "verb", "de": "drucken", "ar": "طَبَعَ", "pres": "يَطْبَعُ"},
    {"cat": "Verben", "type": "verb", "de": "drücken", "ar": "ضَغَطَ", "pres": "يَضْغَطُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "sich entschuldigen", "ar": "اِعْتَذَرَ", "pres": "يَعْتَذِرُ", "prep": "عَنْ"},
    {"cat": "Verben", "type": "verb", "de": "erinnern (jemanden)", "ar": "ذَكَّرَ", "pres": "يُذَكِّرُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "kennenlernen", "ar": "تَعَرَّفَ", "pres": "يَتَعَرَّفُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "erreichen", "ar": "بَلَغَ", "pres": "يَبْلُغُ"},
    {"cat": "Verben", "type": "verb", "de": "erwarten", "ar": "تَوَقَّعَ", "pres": "يَتَوَقَّعُ"},
    {"cat": "Verben", "type": "verb", "de": "leiten, führen", "ar": "أَدَارَ", "pres": "يُدِيرُ"},
    {"cat": "Verben", "type": "verb", "de": "sich gewöhnen", "ar": "اِعْتَادَ", "pres": "يَعْتَادُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "grüßen", "ar": "سَلَّمَ", "pres": "يُسَلِّمُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "heiraten", "ar": "تَزَوَّجَ", "pres": "يَتَزَوَّجُ", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "herstellen", "ar": "أَنْتَجَ", "pres": "يُنْتِجُ"},
    {"cat": "Verben", "type": "verb", "de": "hoffen", "ar": "أَمِلَ", "pres": "يَأْمَلُ", "prep": "فِي"},
    {"cat": "Verben", "type": "verb", "de": "wünschen", "ar": "تَمَنَّى", "pres": "يَتَمَنَّى"},
    {"cat": "Verben", "type": "verb", "de": "kämpfen", "ar": "قَاتَلَ", "pres": "يُقَاتِلُ"},
    {"cat": "Verben", "type": "verb", "de": "klopfen", "ar": "طَرَقَ", "pres": "يَطْرُقُ"},
    {"cat": "Verben", "type": "verb", "de": "kosten (Preis)", "ar": "كَلَّفَ", "pres": "يُكَلِّفُ"},
    {"cat": "Verben", "type": "verb", "de": "sich kümmern", "ar": "اِهْتَمَّ", "pres": "يَهْتَمُّ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "herunterladen", "ar": "حَمَّلَ", "pres": "يُحَمِّلُ"},
    {"cat": "Verben", "type": "verb", "de": "ausleihen (sich)", "ar": "اِسْتَعَارَ", "pres": "يَسْتَعِيرُ", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "verleihen", "ar": "أَعَارَ", "pres": "يُعِيرُ"},
    {"cat": "Verben", "type": "verb", "de": "lösen (ein Problem)", "ar": "حَلَّ", "pres": "يَحُلُّ"},
    {"cat": "Verben", "type": "verb", "de": "zeichnen, malen", "ar": "رَسَمَ", "pres": "يَرْسُمُ"},
    {"cat": "Verben", "type": "verb", "de": "messen", "ar": "قَاسَ", "pres": "يَقِيسُ"},
    {"cat": "Verben", "type": "verb", "de": "mieten", "ar": "اِسْتَأْجَرَ", "pres": "يَسْتَأْجِرُ"},
    {"cat": "Verben", "type": "verb", "de": "mischen", "ar": "خَلَطَ", "pres": "يَخْلِطُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "umziehen, wechseln (Ort)", "ar": "اِنْتَقَلَ", "pres": "يَنْتَقِلُ", "prep": "إِلَى"},
    {"cat": "Verben", "type": "verb", "de": "nennen", "ar": "سَمَّى", "pres": "يُسَمِّي"},
    {"cat": "Verben", "type": "verb", "de": "profitieren", "ar": "اِسْتَفَادَ", "pres": "يَسْتَفِيدُ", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "sich vorbereiten", "ar": "اِسْتَعَدَّ", "pres": "يَسْتَعِدُّ", "prep": "لِ"},
    {"cat": "Verben", "type": "verb", "de": "vorbereiten", "ar": "حَضَّرَ", "pres": "يُحَضِّرُ"},
    {"cat": "Verben", "type": "verb", "de": "rauchen", "ar": "دَخَّنَ", "pres": "يُدَخِّنُ"},
    {"cat": "Verben", "type": "verb", "de": "rechnen, zählen", "ar": "حَسَبَ", "pres": "يَحْسُبُ"},
    {"cat": "Verben", "type": "verb", "de": "regnen", "ar": "أَمْطَرَ", "pres": "يُمْطِرُ",
     "note": "meist: تُمْطِرُ السَّمَاءُ – der Himmel regnet"},
    {"cat": "Verben", "type": "verb", "de": "retten", "ar": "أَنْقَذَ", "pres": "يُنْقِذُ", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "riechen", "ar": "شَمَّ", "pres": "يَشُمُّ"},
    {"cat": "Verben", "type": "verb", "de": "rufen", "ar": "نَادَى", "pres": "يُنَادِي", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "sammeln", "ar": "جَمَعَ", "pres": "يَجْمَعُ"},
    {"cat": "Verben", "type": "verb", "de": "schenken", "ar": "أَهْدَى", "pres": "يُهْدِي", "prep": "إِلَى"},
    {"cat": "Verben", "type": "verb", "de": "kosten, probieren (Geschmack)", "ar": "ذَاقَ", "pres": "يَذُوقُ"},
    {"cat": "Verben", "type": "verb", "de": "schützen", "ar": "حَمَى", "pres": "يَحْمِي", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "schweigen", "ar": "سَكَتَ", "pres": "يَسْكُتُ"},
    {"cat": "Verben", "type": "verb", "de": "singen", "ar": "غَنَّى", "pres": "يُغَنِّي"},
    {"cat": "Verben", "type": "verb", "de": "sich sorgen", "ar": "قَلِقَ", "pres": "يَقْلَقُ", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "sparen", "ar": "وَفَّرَ", "pres": "يُوَفِّرُ"},
    {"cat": "Verben", "type": "verb", "de": "spazieren gehen", "ar": "تَنَزَّهَ", "pres": "يَتَنَزَّهُ"},
    {"cat": "Verben", "type": "verb", "de": "stehlen", "ar": "سَرَقَ", "pres": "يَسْرِقُ", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "steigen, hinaufgehen", "ar": "صَعِدَ", "pres": "يَصْعَدُ", "prep": "إِلَى"},
    {"cat": "Verben", "type": "verb", "de": "stören", "ar": "أَزْعَجَ", "pres": "يُزْعِجُ"},
    {"cat": "Verben", "type": "verb", "de": "streiten", "ar": "تَشَاجَرَ", "pres": "يَتَشَاجَرُ", "prep": "مَعَ"},
    {"cat": "Verben", "type": "verb", "de": "tanzen", "ar": "رَقَصَ", "pres": "يَرْقُصُ"},
    {"cat": "Verben", "type": "verb", "de": "teilen, aufteilen", "ar": "قَسَّمَ", "pres": "يُقَسِّمُ", "prep": "إِلَى"},
    {"cat": "Verben", "type": "verb", "de": "teilnehmen", "ar": "شَارَكَ", "pres": "يُشَارِكُ", "prep": "فِي"},
    {"cat": "Verben", "type": "verb", "de": "töten", "ar": "قَتَلَ", "pres": "يَقْتُلُ"},
    {"cat": "Verben", "type": "verb", "de": "träumen", "ar": "حَلِمَ", "pres": "يَحْلُمُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "trocknen", "ar": "جَفَّفَ", "pres": "يُجَفِّفُ"},
    {"cat": "Verben", "type": "verb", "de": "überqueren", "ar": "عَبَرَ", "pres": "يَعْبُرُ"},
    {"cat": "Verben", "type": "verb", "de": "übersetzen", "ar": "تَرْجَمَ", "pres": "يُتَرْجِمُ", "prep": "إِلَى"},
    {"cat": "Verben", "type": "verb", "de": "überzeugen", "ar": "أَقْنَعَ", "pres": "يُقْنِعُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "umarmen", "ar": "عَانَقَ", "pres": "يُعَانِقُ"},
    {"cat": "Verben", "type": "verb", "de": "unterschreiben", "ar": "وَقَّعَ", "pres": "يُوَقِّعُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "unterstützen", "ar": "دَعَمَ", "pres": "يَدْعَمُ"},
    {"cat": "Verben", "type": "verb", "de": "untersuchen (ärztlich)", "ar": "فَحَصَ", "pres": "يَفْحَصُ"},
    {"cat": "Verben", "type": "verb", "de": "verbessern", "ar": "حَسَّنَ", "pres": "يُحَسِّنُ"},
    {"cat": "Verben", "type": "verb", "de": "verbinden, festbinden", "ar": "رَبَطَ", "pres": "يَرْبِطُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "verbringen (Zeit)", "ar": "قَضَى", "pres": "يَقْضِي"},
    {"cat": "Verben", "type": "verb", "de": "vergleichen", "ar": "قَارَنَ", "pres": "يُقَارِنُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "sich verspäten", "ar": "تَأَخَّرَ", "pres": "يَتَأَخَّرُ", "prep": "عَنْ"},
    {"cat": "Verben", "type": "verb", "de": "verteidigen", "ar": "دَافَعَ", "pres": "يُدَافِعُ", "prep": "عَنْ"},
    {"cat": "Verben", "type": "verb", "de": "vertrauen", "ar": "وَثِقَ", "pres": "يَثِقُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "verzeihen", "ar": "سَامَحَ", "pres": "يُسَامِحُ"},
    {"cat": "Verben", "type": "verb", "de": "vorschlagen", "ar": "اِقْتَرَحَ", "pres": "يَقْتَرِحُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "sich vorstellen (im Kopf)", "ar": "تَخَيَّلَ", "pres": "يَتَخَيَّلُ"},
    {"cat": "Verben", "type": "verb", "de": "wachsen", "ar": "نَمَا", "pres": "يَنْمُو"},
    {"cat": "Verben", "type": "verb", "de": "wiederholen", "ar": "كَرَّرَ", "pres": "يُكَرِّرُ"},
    {"cat": "Verben", "type": "verb", "de": "wiegen", "ar": "وَزَنَ", "pres": "يَزِنُ"},
    {"cat": "Verben", "type": "verb", "de": "sich wundern", "ar": "تَعَجَّبَ", "pres": "يَتَعَجَّبُ", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "zeigen", "ar": "أَظْهَرَ", "pres": "يُظْهِرُ"},
    {"cat": "Verben", "type": "verb", "de": "hinweisen, deuten", "ar": "أَشَارَ", "pres": "يُشِيرُ", "prep": "إِلَى"},
    {"cat": "Verben", "type": "verb", "de": "zerstören", "ar": "دَمَّرَ", "pres": "يُدَمِّرُ"},
    {"cat": "Verben", "type": "verb", "de": "ziehen", "ar": "سَحَبَ", "pres": "يَسْحَبُ"},
    {"cat": "Verben", "type": "verb", "de": "zurückgeben", "ar": "أَعَادَ", "pres": "يُعِيدُ", "prep": "إِلَى"},
    {"cat": "Verben", "type": "verb", "de": "zusammenarbeiten", "ar": "تَعَاوَنَ", "pres": "يَتَعَاوَنُ", "prep": "مَعَ"},
    {"cat": "Verben", "type": "verb", "de": "zwingen", "ar": "أَجْبَرَ", "pres": "يُجْبِرُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "aufpassen, achtgeben", "ar": "اِنْتَبَهَ", "pres": "يَنْتَبِهُ", "prep": "إِلَى"},
    {"cat": "Verben", "type": "verb", "de": "ausdrücken", "ar": "عَبَّرَ", "pres": "يُعَبِّرُ", "prep": "عَنْ"},
    {"cat": "Verben", "type": "verb", "de": "bedeuten", "ar": "عَنَى", "pres": "يَعْنِي"},
    {"cat": "Verben", "type": "verb", "de": "befehlen", "ar": "أَمَرَ", "pres": "يَأْمُرُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "berühren", "ar": "لَمَسَ", "pres": "يَلْمِسُ"},
    {"cat": "Verben", "type": "verb", "de": "bestrafen", "ar": "عَاقَبَ", "pres": "يُعَاقِبُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "urteilen, richten", "ar": "حَكَمَ", "pres": "يَحْكُمُ", "prep": "عَلَى"},
    {"cat": "Verben", "type": "verb", "de": "verbrennen (selbst)", "ar": "اِحْتَرَقَ", "pres": "يَحْتَرِقُ"},
    {"cat": "Verben", "type": "verb", "de": "duschen, baden", "ar": "اِسْتَحَمَّ", "pres": "يَسْتَحِمُّ"},
    {"cat": "Verben", "type": "verb", "de": "raten, empfehlen", "ar": "نَصَحَ", "pres": "يَنْصَحُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "entdecken", "ar": "اِكْتَشَفَ", "pres": "يَكْتَشِفُ"},
    {"cat": "Verben", "type": "verb", "de": "entwickeln", "ar": "طَوَّرَ", "pres": "يُطَوِّرُ"},
    {"cat": "Verben", "type": "verb", "de": "erziehen, großziehen", "ar": "رَبَّى", "pres": "يُرَبِّي"},
    {"cat": "Verben", "type": "verb", "de": "genießen", "ar": "اِسْتَمْتَعَ", "pres": "يَسْتَمْتِعُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "gießen, tränken", "ar": "سَقَى", "pres": "يَسْقِي"},
    {"cat": "Verben", "type": "verb", "de": "gratulieren", "ar": "هَنَّأَ", "pres": "يُهَنِّئُ", "prep": "بِ"},
    {"cat": "Verben", "type": "verb", "de": "behandeln (ärztlich)", "ar": "عَالَجَ", "pres": "يُعَالِجُ", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "hinzufügen", "ar": "أَضَافَ", "pres": "يُضِيفُ", "prep": "إِلَى"},
    {"cat": "Verben", "type": "verb", "de": "leiden", "ar": "عَانَى", "pres": "يُعَانِي", "prep": "مِنْ"},
    {"cat": "Verben", "type": "verb", "de": "loben", "ar": "مَدَحَ", "pres": "يَمْدَحُ"},
    {"cat": "Verben", "type": "verb", "de": "löschen, streichen", "ar": "حَذَفَ", "pres": "يَحْذِفُ"},
    {"cat": "Verben", "type": "verb", "de": "nähen", "ar": "خَاطَ", "pres": "يَخِيطُ"},
    {"cat": "Verben", "type": "verb", "de": "pflanzen, säen", "ar": "زَرَعَ", "pres": "يَزْرَعُ"},
    {"cat": "Verben", "type": "verb", "de": "prüfen, testen", "ar": "اِخْتَبَرَ", "pres": "يَخْتَبِرُ"},
    {"cat": "Verben", "type": "verb", "de": "rasieren", "ar": "حَلَقَ", "pres": "يَحْلِقُ"},
    {"cat": "Verben", "type": "verb", "de": "wehtun, schmerzen", "ar": "آلَمَ", "pres": "يُؤْلِمُ",
     "note": "يُؤْلِمُنِي رَأْسِي – mein Kopf tut mir weh"},

    # ================= Essen und Trinken (Ergänzung) =================
    {"cat": "Essen und Trinken", "type": "noun", "de": "Suppe", "ar": "حَسَاءٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Salat", "ar": "سَلَطَةٌ", "pl": "سَلَطَاتٌ", "g": "f"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Honig", "ar": "عَسَلٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Mehl", "ar": "دَقِيقٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Gurke", "ar": "خِيَارٌ", "pl": None, "g": "m",
     "note": "Sammelwort; eine einzelne: خِيَارَةٌ"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Karotte", "ar": "جَزَرٌ", "pl": None, "g": "m",
     "note": "Sammelwort; eine einzelne: جَزَرَةٌ"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Zitrone", "ar": "لَيْمُونٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Feige", "ar": "تِينٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Granatapfel", "ar": "رُمَّانٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Olive", "ar": "زَيْتُونٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Walnuss", "ar": "جَوْزٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Mandel", "ar": "لَوْزٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Knoblauch", "ar": "ثُومٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Gewürz", "ar": "بَهَارٌ", "pl": "بَهَارَاتٌ", "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Kuchen", "ar": "كَعْكَةٌ", "pl": "كَعْكَاتٌ", "g": "f"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Süßigkeiten", "ar": "حَلْوَى", "pl": "حَلْوَيَاتٌ", "g": "f"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Schokolade", "ar": "شُوكُولَاتَةٌ", "pl": None, "g": "f"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Teller", "ar": "طَبَقٌ", "pl": "أَطْبَاقٌ", "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Tasse", "ar": "فِنْجَانٌ", "pl": "فَنَاجِينُ", "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Gabel", "ar": "شَوْكَةٌ", "pl": "شِوَكٌ", "g": "f"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Messer", "ar": "سِكِّينٌ", "pl": "سَكَاكِينُ", "g": "f",
     "note": "wird auch männlich gebraucht"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Getränk", "ar": "مَشْرُوبٌ", "pl": "مَشْرُوبَاتٌ", "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Geschmack", "ar": "طَعْمٌ", "pl": "طُعُومٌ", "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Rezept (Kochen)", "ar": "وَصْفَةٌ", "pl": "وَصْفَاتٌ", "g": "f"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Hunger", "ar": "جُوعٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Durst", "ar": "عَطَشٌ", "pl": None, "g": "m"},
    {"cat": "Essen und Trinken", "type": "noun", "de": "Rindfleisch", "ar": "لَحْمُ بَقَرٍ", "pl": None, "g": "m"},

    # ================= Haus und Alltag (Ergänzung) =================
    {"cat": "Haus und Alltag", "type": "noun", "de": "Sofa", "ar": "أَرِيكَةٌ", "pl": "أَرَائِكُ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Teppich", "ar": "سَجَّادَةٌ", "pl": "سَجَاجِيدُ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Vorhang", "ar": "سِتَارَةٌ", "pl": "سَتَائِرُ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Kissen", "ar": "وِسَادَةٌ", "pl": "وَسَائِدُ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Wolldecke", "ar": "بَطَّانِيَّةٌ", "pl": "بَطَّانِيَّاتٌ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Backofen, Herd", "ar": "فُرْنٌ", "pl": "أَفْرَانٌ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Müll", "ar": "قُمَامَةٌ", "pl": None, "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Besen", "ar": "مِكْنَسَةٌ", "pl": "مَكَانِسُ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Waschbecken", "ar": "مَغْسَلَةٌ", "pl": "مَغَاسِلُ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Dusche", "ar": "دُشٌّ", "pl": "أَدْشَاشٌ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Zahnbürste", "ar": "فُرْشَاةُ أَسْنَانٍ", "pl": None, "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Zahnpasta", "ar": "مَعْجُونُ أَسْنَانٍ", "pl": None, "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Kamm", "ar": "مُشْطٌ", "pl": "أَمْشَاطٌ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Schere", "ar": "مِقَصٌّ", "pl": "مَقَاصُّ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Nadel", "ar": "إِبْرَةٌ", "pl": "إِبَرٌ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Faden", "ar": "خَيْطٌ", "pl": "خُيُوطٌ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Nagel (Werkzeug)", "ar": "مِسْمَارٌ", "pl": "مَسَامِيرُ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Hammer", "ar": "مِطْرَقَةٌ", "pl": "مَطَارِقُ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Schublade", "ar": "دُرْجٌ", "pl": "أَدْرَاجٌ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Regal", "ar": "رَفٌّ", "pl": "رُفُوفٌ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Klimaanlage", "ar": "مُكَيِّفٌ", "pl": "مُكَيِّفَاتٌ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Heizung", "ar": "تَدْفِئَةٌ", "pl": None, "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Strom", "ar": "كَهْرَبَاءُ", "pl": None, "g": "f",
     "note": "kein Tanwin – das Wort ist diptot"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Wasserhahn", "ar": "صُنْبُورٌ", "pl": "صَنَابِيرُ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Balkon", "ar": "شُرْفَةٌ", "pl": "شُرَفٌ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Aufzug", "ar": "مِصْعَدٌ", "pl": "مَصَاعِدُ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Stockwerk", "ar": "طَابِقٌ", "pl": "طَوَابِقُ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Miete", "ar": "إِيجَارٌ", "pl": "إِيجَارَاتٌ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Stadtviertel", "ar": "حَيٌّ", "pl": "أَحْيَاءٌ", "g": "m",
     "note": "dasselbe Wort heißt als Adjektiv „lebendig“"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Wecker", "ar": "مُنَبِّهٌ", "pl": "مُنَبِّهَاتٌ", "g": "m"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Kerze", "ar": "شَمْعَةٌ", "pl": "شُمُوعٌ", "g": "f"},
    {"cat": "Haus und Alltag", "type": "noun", "de": "Schloss (an der Tür)", "ar": "قُفْلٌ", "pl": "أَقْفَالٌ", "g": "m"},

    # ================= Körper und Gesundheit (Ergänzung) =================
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Haar", "ar": "شَعْرٌ", "pl": "شُعُورٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Hals (außen)", "ar": "رَقَبَةٌ", "pl": "رِقَابٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Kehle", "ar": "حَلْقٌ", "pl": "حُلُوقٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Schulter", "ar": "كَتِفٌ", "pl": "أَكْتَافٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Knie", "ar": "رُكْبَةٌ", "pl": "رُكَبٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Ellbogen", "ar": "مِرْفَقٌ", "pl": "مَرَافِقُ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Haut", "ar": "جِلْدٌ", "pl": "جُلُودٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Knochen", "ar": "عَظْمٌ", "pl": "عِظَامٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Muskel", "ar": "عَضَلَةٌ", "pl": "عَضَلَاتٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Lunge", "ar": "رِئَةٌ", "pl": "رِئَاتٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Leber", "ar": "كَبِدٌ", "pl": "أَكْبَادٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Magen", "ar": "مَعِدَةٌ", "pl": "مَعِدَاتٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Gehirn", "ar": "دِمَاغٌ", "pl": "أَدْمِغَةٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Nerv", "ar": "عَصَبٌ", "pl": "أَعْصَابٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Stirn", "ar": "جَبِينٌ", "pl": "أَجْبِنَةٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Wange", "ar": "خَدٌّ", "pl": "خُدُودٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Lippe", "ar": "شَفَةٌ", "pl": "شِفَاهٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Augenbraue", "ar": "حَاجِبٌ", "pl": "حَوَاجِبُ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Bart", "ar": "لِحْيَةٌ", "pl": "لِحًى", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Schnurrbart", "ar": "شَارِبٌ", "pl": "شَوَارِبُ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Fingernagel", "ar": "ظُفْرٌ", "pl": "أَظَافِرُ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Verletzung", "ar": "إِصَابَةٌ", "pl": "إِصَابَاتٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Husten", "ar": "سُعَالٌ", "pl": None, "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Erkältung", "ar": "زُكَامٌ", "pl": None, "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Kopfschmerzen", "ar": "صُدَاعٌ", "pl": None, "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Allergie", "ar": "حَسَاسِيَّةٌ", "pl": None, "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Spritze", "ar": "حُقْنَةٌ", "pl": "حُقَنٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Behandlung", "ar": "عِلَاجٌ", "pl": "عِلَاجَاتٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Operation", "ar": "عَمَلِيَّةٌ", "pl": "عَمَلِيَّاتٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Krankenwagen", "ar": "سَيَّارَةُ إِسْعَافٍ", "pl": None, "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Apotheke", "ar": "صَيْدَلِيَّةٌ", "pl": "صَيْدَلِيَّاتٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Impfung", "ar": "تَطْعِيمٌ", "pl": "تَطْعِيمَاتٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Sport", "ar": "رِيَاضَةٌ", "pl": "رِيَاضَاتٌ", "g": "f"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Gewicht", "ar": "وَزْنٌ", "pl": "أَوْزَانٌ", "g": "m"},
    {"cat": "Körper und Gesundheit", "type": "noun", "de": "Atem", "ar": "نَفَسٌ", "pl": "أَنْفَاسٌ", "g": "m"},

    # ================= Orte und Reisen (Ergänzung) =================
    {"cat": "Orte und Reisen", "type": "noun", "de": "Hafen", "ar": "مِينَاءٌ", "pl": "مَوَانِئُ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Schiff", "ar": "سَفِينَةٌ", "pl": "سُفُنٌ", "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Boot", "ar": "قَارِبٌ", "pl": "قَوَارِبُ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Grenze", "ar": "حَدٌّ", "pl": "حُدُودٌ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Visum", "ar": "تَأْشِيرَةٌ", "pl": "تَأْشِيرَاتٌ", "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Gepäck", "ar": "أَمْتِعَةٌ", "pl": None, "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Zoll", "ar": "جُمْرُكٌ", "pl": "جَمَارِكُ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Botschaft (Vertretung)", "ar": "سِفَارَةٌ", "pl": "سِفَارَاتٌ", "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Wüste", "ar": "صَحْرَاءُ", "pl": "صَحَارَى", "g": "f",
     "note": "kein Tanwin – das Wort ist diptot"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Fluss", "ar": "نَهْرٌ", "pl": "أَنْهَارٌ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "See (Gewässer)", "ar": "بُحَيْرَةٌ", "pl": "بُحَيْرَاتٌ", "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Insel", "ar": "جَزِيرَةٌ", "pl": "جُزُرٌ", "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Tal", "ar": "وَادٍ", "pl": "أَوْدِيَةٌ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Hügel", "ar": "تَلٌّ", "pl": "تِلَالٌ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Feld", "ar": "حَقْلٌ", "pl": "حُقُولٌ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Bauernhof", "ar": "مَزْرَعَةٌ", "pl": "مَزَارِعُ", "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Platz (in der Stadt)", "ar": "سَاحَةٌ", "pl": "سَاحَاتٌ", "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Gasse", "ar": "زُقَاقٌ", "pl": "أَزِقَّةٌ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Ecke", "ar": "زَاوِيَةٌ", "pl": "زَوَايَا", "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Richtung", "ar": "اِتِّجَاهٌ", "pl": "اِتِّجَاهَاتٌ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Norden", "ar": "شَمَالٌ", "pl": None, "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Süden", "ar": "جَنُوبٌ", "pl": None, "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Osten", "ar": "شَرْقٌ", "pl": None, "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Westen", "ar": "غَرْبٌ", "pl": None, "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Entfernung", "ar": "مَسَافَةٌ", "pl": "مَسَافَاتٌ", "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Führerschein", "ar": "رُخْصَةُ قِيَادَةٍ", "pl": None, "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Tankstelle", "ar": "مَحَطَّةُ وَقُودٍ", "pl": None, "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Benzin", "ar": "بَنْزِينٌ", "pl": None, "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Unfall", "ar": "حَادِثٌ", "pl": "حَوَادِثُ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Ampel", "ar": "إِشَارَةُ مُرُورٍ", "pl": None, "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Bürgersteig", "ar": "رَصِيفٌ", "pl": "أَرْصِفَةٌ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Taxi", "ar": "سَيَّارَةُ أُجْرَةٍ", "pl": None, "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Verspätung", "ar": "تَأْخِيرٌ", "pl": "تَأْخِيرَاتٌ", "g": "m"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Abreise, Abflug", "ar": "مُغَادَرَةٌ", "pl": None, "g": "f"},
    {"cat": "Orte und Reisen", "type": "noun", "de": "Ankunft", "ar": "وُصُولٌ", "pl": None, "g": "m"},

    # ================= Natur, Wetter und Dinge (Ergänzung) =================
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Stern", "ar": "نَجْمٌ", "pl": "نُجُومٌ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Schnee", "ar": "ثَلْجٌ", "pl": "ثُلُوجٌ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Sturm", "ar": "عَاصِفَةٌ", "pl": "عَوَاصِفُ", "g": "f"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Nebel", "ar": "ضَبَابٌ", "pl": None, "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Donner", "ar": "رَعْدٌ", "pl": None, "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Blitz", "ar": "بَرْقٌ", "pl": None, "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Wetter", "ar": "طَقْسٌ", "pl": None, "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Schatten", "ar": "ظِلٌّ", "pl": "ظِلَالٌ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Licht", "ar": "نُورٌ", "pl": "أَنْوَارٌ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Dunkelheit", "ar": "ظَلَامٌ", "pl": None, "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Stein", "ar": "حَجَرٌ", "pl": "حِجَارَةٌ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Sand", "ar": "رَمْلٌ", "pl": "رِمَالٌ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Staub", "ar": "غُبَارٌ", "pl": None, "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Holz", "ar": "خَشَبٌ", "pl": "أَخْشَابٌ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Eisen", "ar": "حَدِيدٌ", "pl": None, "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Glas (Material)", "ar": "زُجَاجٌ", "pl": None, "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Papier", "ar": "وَرَقٌ", "pl": "أَوْرَاقٌ", "g": "m",
     "note": "ein einzelnes Blatt: وَرَقَةٌ"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Wurzel", "ar": "جَذْرٌ", "pl": "جُذُورٌ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Zweig", "ar": "غُصْنٌ", "pl": "أَغْصَانٌ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Samenkorn", "ar": "بَذْرَةٌ", "pl": "بُذُورٌ", "g": "f"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Frucht", "ar": "ثَمَرَةٌ", "pl": "ثِمَارٌ", "g": "f"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Welt", "ar": "عَالَمٌ", "pl": "عَوَالِمُ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Natur", "ar": "طَبِيعَةٌ", "pl": None, "g": "f"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Umwelt", "ar": "بِيئَةٌ", "pl": "بِيئَاتٌ", "g": "f"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Klima", "ar": "مَنَاخٌ", "pl": None, "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Feuchtigkeit", "ar": "رُطُوبَةٌ", "pl": None, "g": "f"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Welle", "ar": "مَوْجَةٌ", "pl": "أَمْوَاجٌ", "g": "f"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Küste", "ar": "سَاحِلٌ", "pl": "سَوَاحِلُ", "g": "m"},
    {"cat": "Natur, Wetter und Dinge", "type": "noun", "de": "Höhle", "ar": "كَهْفٌ", "pl": "كُهُوفٌ", "g": "m"},

    # ================= Tiere =================
    {"cat": "Tiere", "type": "noun", "de": "Pferd", "ar": "حِصَانٌ", "pl": "أَحْصِنَةٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Kamel", "ar": "جَمَلٌ", "pl": "جِمَالٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Kuh", "ar": "بَقَرَةٌ", "pl": "بَقَرَاتٌ", "g": "f"},
    {"cat": "Tiere", "type": "noun", "de": "Schaf", "ar": "خَرُوفٌ", "pl": "خِرَافٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Ziege", "ar": "مَاعِزٌ", "pl": "مَوَاعِزُ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Esel", "ar": "حِمَارٌ", "pl": "حَمِيرٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Löwe", "ar": "أَسَدٌ", "pl": "أُسُودٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Wolf", "ar": "ذِئْبٌ", "pl": "ذِئَابٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Fuchs", "ar": "ثَعْلَبٌ", "pl": "ثَعَالِبُ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Bär", "ar": "دُبٌّ", "pl": "دِبَبَةٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Elefant", "ar": "فِيلٌ", "pl": "أَفْيَالٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Affe", "ar": "قِرْدٌ", "pl": "قُرُودٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Maus", "ar": "فَأْرٌ", "pl": "فِئْرَانٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Schlange", "ar": "ثُعْبَانٌ", "pl": "ثَعَابِينُ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Fliege", "ar": "ذُبَابَةٌ", "pl": "ذُبَابٌ", "g": "f"},
    {"cat": "Tiere", "type": "noun", "de": "Mücke", "ar": "بَعُوضَةٌ", "pl": "بَعُوضٌ", "g": "f"},
    {"cat": "Tiere", "type": "noun", "de": "Biene", "ar": "نَحْلَةٌ", "pl": "نَحْلٌ", "g": "f"},
    {"cat": "Tiere", "type": "noun", "de": "Ameise", "ar": "نَمْلَةٌ", "pl": "نَمْلٌ", "g": "f"},
    {"cat": "Tiere", "type": "noun", "de": "Spinne", "ar": "عَنْكَبُوتٌ", "pl": "عَنَاكِبُ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Taube", "ar": "حَمَامَةٌ", "pl": "حَمَامٌ", "g": "f"},
    {"cat": "Tiere", "type": "noun", "de": "Hahn", "ar": "دِيكٌ", "pl": "دِيَكَةٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Feder (Vogel)", "ar": "رِيشَةٌ", "pl": "رِيشٌ", "g": "f"},
    {"cat": "Tiere", "type": "noun", "de": "Flügel", "ar": "جَنَاحٌ", "pl": "أَجْنِحَةٌ", "g": "m"},
    {"cat": "Tiere", "type": "noun", "de": "Schwanz", "ar": "ذَيْلٌ", "pl": "ذُيُولٌ", "g": "m"},

    # ================= Stadt und Einkaufen =================
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Bank (Geldhaus)", "ar": "مَصْرِفٌ", "pl": "مَصَارِفُ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Post", "ar": "بَرِيدٌ", "pl": None, "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Brief", "ar": "رِسَالَةٌ", "pl": "رَسَائِلُ", "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Paket", "ar": "طَرْدٌ", "pl": "طُرُودٌ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Briefmarke", "ar": "طَابِعٌ", "pl": "طَوَابِعُ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Bäckerei", "ar": "مَخْبَزٌ", "pl": "مَخَابِزُ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Metzgerei", "ar": "مَلْحَمَةٌ", "pl": "مَلَاحِمُ", "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Lebensmittelladen", "ar": "بَقَّالَةٌ", "pl": "بَقَّالَاتٌ", "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Museum", "ar": "مَتْحَفٌ", "pl": "مَتَاحِفُ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Theater", "ar": "مَسْرَحٌ", "pl": "مَسَارِحُ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Polizei", "ar": "شُرْطَةٌ", "pl": None, "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Gefängnis", "ar": "سِجْنٌ", "pl": "سُجُونٌ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Gericht (Behörde)", "ar": "مَحْكَمَةٌ", "pl": "مَحَاكِمُ", "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Geldbörse", "ar": "مَحْفَظَةٌ", "pl": "مَحَافِظُ", "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Währung", "ar": "عُمْلَةٌ", "pl": "عُمْلَاتٌ", "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Rechnung", "ar": "فَاتُورَةٌ", "pl": "فَوَاتِيرُ", "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Quittung", "ar": "إِيصَالٌ", "pl": "إِيصَالَاتٌ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Rabatt", "ar": "خَصْمٌ", "pl": "خُصُومَاتٌ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Angebot", "ar": "عَرْضٌ", "pl": "عُرُوضٌ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Kunde", "ar": "زَبُونٌ", "pl": "زَبَائِنُ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Warteschlange", "ar": "طَابُورٌ", "pl": "طَوَابِيرُ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Kosten", "ar": "تَكْلِفَةٌ", "pl": "تَكَالِيفُ", "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Steuer", "ar": "ضَرِيبَةٌ", "pl": "ضَرَائِبُ", "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Konto", "ar": "حِسَابٌ", "pl": "حِسَابَاتٌ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Werbung, Anzeige", "ar": "إِعْلَانٌ", "pl": "إِعْلَانَاتٌ", "g": "m"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Qualität", "ar": "جَوْدَةٌ", "pl": None, "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Ware", "ar": "بِضَاعَةٌ", "pl": "بَضَائِعُ", "g": "f"},
    {"cat": "Stadt und Einkaufen", "type": "noun", "de": "Einladung", "ar": "دَعْوَةٌ", "pl": "دَعَوَاتٌ", "g": "f"},

    # ================= Technik und Medien =================
    {"cat": "Technik und Medien", "type": "noun", "de": "Handy", "ar": "جَوَّالٌ", "pl": "جَوَّالَاتٌ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Bildschirm", "ar": "شَاشَةٌ", "pl": "شَاشَاتٌ", "g": "f"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Netz, Netzwerk", "ar": "شَبَكَةٌ", "pl": "شَبَكَاتٌ", "g": "f"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Programm, App", "ar": "بَرْنَامَجٌ", "pl": "بَرَامِجُ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Datei", "ar": "مِلَفٌّ", "pl": "مِلَفَّاتٌ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Passwort", "ar": "كَلِمَةُ مُرُورٍ", "pl": None, "g": "f"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Zeitung", "ar": "جَرِيدَةٌ", "pl": "جَرَائِدُ", "g": "f"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Zeitschrift", "ar": "مَجَلَّةٌ", "pl": "مَجَلَّاتٌ", "g": "f"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Rundfunk", "ar": "إِذَاعَةٌ", "pl": "إِذَاعَاتٌ", "g": "f"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Sender, Kanal", "ar": "قَنَاةٌ", "pl": "قَنَوَاتٌ", "g": "f"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Bericht", "ar": "تَقْرِيرٌ", "pl": "تَقَارِيرُ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Artikel (Text)", "ar": "مَقَالٌ", "pl": "مَقَالَاتٌ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Schriftsteller", "ar": "كَاتِبٌ", "pl": "كُتَّابٌ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Leser", "ar": "قَارِئٌ", "pl": "قُرَّاءٌ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Information", "ar": "مَعْلُومَةٌ", "pl": "مَعْلُومَاتٌ", "g": "f"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Wissenschaft", "ar": "عِلْمٌ", "pl": "عُلُومٌ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Forschung", "ar": "بَحْثٌ", "pl": "بُحُوثٌ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Erfindung", "ar": "اِخْتِرَاعٌ", "pl": "اِخْتِرَاعَاتٌ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Maschine", "ar": "آلَةٌ", "pl": "آلَاتٌ", "g": "f"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Motor", "ar": "مُحَرِّكٌ", "pl": "مُحَرِّكَاتٌ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Batterie", "ar": "بَطَّارِيَّةٌ", "pl": "بَطَّارِيَّاتٌ", "g": "f"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Knopf, Taste", "ar": "زِرٌّ", "pl": "أَزْرَارٌ", "g": "m"},
    {"cat": "Technik und Medien", "type": "noun", "de": "Kabel", "ar": "سِلْكٌ", "pl": "أَسْلَاكٌ", "g": "m"},

    # ================= Gefühle und Charakter =================
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Gefühl", "ar": "شُعُورٌ", "pl": "مَشَاعِرُ", "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Freude", "ar": "فَرَحٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Glück (Zustand)", "ar": "سَعَادَةٌ", "pl": None, "g": "f"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Trauer", "ar": "حُزْنٌ", "pl": "أَحْزَانٌ", "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Angst", "ar": "خَوْفٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Wut", "ar": "غَضَبٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Liebe", "ar": "حُبٌّ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Hass", "ar": "كُرْهٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Hoffnung", "ar": "أَمَلٌ", "pl": "آمَالٌ", "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Geduld", "ar": "صَبْرٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Vertrauen", "ar": "ثِقَةٌ", "pl": None, "g": "f"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Mut", "ar": "شَجَاعَةٌ", "pl": None, "g": "f"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Ehrlichkeit", "ar": "صِدْقٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Lüge", "ar": "كَذِبٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Neid", "ar": "حَسَدٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Bescheidenheit", "ar": "تَوَاضُعٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Großzügigkeit", "ar": "كَرَمٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Geiz", "ar": "بُخْلٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Wesensart", "ar": "طَبْعٌ", "pl": "طِبَاعٌ", "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Verhalten", "ar": "سُلُوكٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Gewohnheit", "ar": "عَادَةٌ", "pl": "عَادَاتٌ", "g": "f"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Meinung", "ar": "رَأْيٌ", "pl": "آرَاءٌ", "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Wunsch", "ar": "رَغْبَةٌ", "pl": "رَغَبَاتٌ", "g": "f"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Traum", "ar": "حُلْمٌ", "pl": "أَحْلَامٌ", "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Erinnerung", "ar": "ذِكْرَى", "pl": "ذِكْرَيَاتٌ", "g": "f"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Erfahrung", "ar": "خِبْرَةٌ", "pl": "خِبْرَاتٌ", "g": "f"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Verstand", "ar": "عَقْلٌ", "pl": "عُقُولٌ", "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Seele", "ar": "رُوحٌ", "pl": "أَرْوَاحٌ", "g": "f"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Sorge, Unruhe", "ar": "قَلَقٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Scham", "ar": "خَجَلٌ", "pl": None, "g": "m"},
    {"cat": "Gefühle und Charakter", "type": "noun", "de": "Freundschaft", "ar": "صَدَاقَةٌ", "pl": "صَدَاقَاتٌ", "g": "f"},

    # ================= Religion und Moschee (Ergänzung) =================
    {"cat": "Religion und Moschee", "type": "noun", "de": "Prophet", "ar": "نَبِيٌّ", "pl": "أَنْبِيَاءُ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Gesandter", "ar": "رَسُولٌ", "pl": "رُسُلٌ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Engel", "ar": "مَلَكٌ", "pl": "مَلَائِكَةٌ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Paradies", "ar": "جَنَّةٌ", "pl": "جِنَانٌ", "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Tag der Auferstehung", "ar": "يَوْمُ الْقِيَامَةِ", "pl": None, "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Sünde", "ar": "ذَنْبٌ", "pl": "ذُنُوبٌ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Reue, Umkehr", "ar": "تَوْبَةٌ", "pl": None, "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Lohn, Belohnung", "ar": "أَجْرٌ", "pl": "أُجُورٌ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Barmherzigkeit", "ar": "رَحْمَةٌ", "pl": None, "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Vergebung", "ar": "مَغْفِرَةٌ", "pl": None, "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Gottesfurcht", "ar": "تَقْوَى", "pl": None, "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Aufrichtigkeit", "ar": "إِخْلَاصٌ", "pl": None, "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Gebetsruf", "ar": "أَذَانٌ", "pl": None, "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Gebetsrichtung", "ar": "قِبْلَةٌ", "pl": None, "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Kanzel", "ar": "مِنْبَرٌ", "pl": "مَنَابِرُ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Minarett", "ar": "مِئْذَنَةٌ", "pl": "مَآذِنُ", "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Kaaba", "ar": "كَعْبَةٌ", "pl": None, "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Almosen (freiwillig)", "ar": "صَدَقَةٌ", "pl": "صَدَقَاتٌ", "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Gebetseinheit", "ar": "رَكْعَةٌ", "pl": "رَكَعَاتٌ", "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Prophetengefährte", "ar": "صَحَابِيٌّ", "pl": "صَحَابَةٌ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Gelehrter", "ar": "عَالِمٌ", "pl": "عُلَمَاءُ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Rechtsschule", "ar": "مَذْهَبٌ", "pl": "مَذَاهِبُ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Prophetenwort (Hadith)", "ar": "حَدِيثٌ", "pl": "أَحَادِيثُ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Sunna, Brauch des Propheten", "ar": "سُنَّةٌ", "pl": "سُنَنٌ", "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Quran-Teil (Juzʾ)", "ar": "جُزْءٌ", "pl": "أَجْزَاءٌ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Rezitation", "ar": "تِلَاوَةٌ", "pl": None, "g": "f"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Lobpreisung", "ar": "تَسْبِيحٌ", "pl": None, "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Gläubiger", "ar": "مُؤْمِنٌ", "pl": "مُؤْمِنُونَ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Pilger", "ar": "حَاجٌّ", "pl": "حُجَّاجٌ", "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Fastenbrechen (abends)", "ar": "إِفْطَارٌ", "pl": None, "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Mahlzeit vor Morgengrauen", "ar": "سُحُورٌ", "pl": None, "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Fest des Fastenbrechens", "ar": "عِيدُ الْفِطْرِ", "pl": None, "g": "m"},
    {"cat": "Religion und Moschee", "type": "noun", "de": "Opferfest", "ar": "عِيدُ الْأَضْحَى", "pl": None, "g": "m"},

    # ================= Studium und Arbeit (Ergänzung) =================
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Wissen, Kenntnis", "ar": "مَعْرِفَةٌ", "pl": None, "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Notiz, Anmerkung", "ar": "مُلَاحَظَةٌ", "pl": "مُلَاحَظَاتٌ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Zeugnis, Abschluss", "ar": "شَهَادَةٌ", "pl": "شَهَادَاتٌ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Note (Bewertung)", "ar": "دَرَجَةٌ", "pl": "دَرَجَاتٌ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Schulfach", "ar": "مَادَّةٌ", "pl": "مَوَادُّ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Mathematik", "ar": "رِيَاضِيَّاتٌ", "pl": None, "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Geschichte, Datum", "ar": "تَارِيخٌ", "pl": None, "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Literatur", "ar": "أَدَبٌ", "pl": "آدَابٌ", "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Übung", "ar": "تَمْرِينٌ", "pl": "تَمَارِينُ", "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Fehler", "ar": "خَطَأٌ", "pl": "أَخْطَاءٌ", "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Ergebnis", "ar": "نَتِيجَةٌ", "pl": "نَتَائِجُ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Ziel", "ar": "هَدَفٌ", "pl": "أَهْدَافٌ", "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Plan", "ar": "خُطَّةٌ", "pl": "خُطَطٌ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Aufgabe", "ar": "مُهِمَّةٌ", "pl": "مَهَامٌّ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Vertrag", "ar": "عَقْدٌ", "pl": "عُقُودٌ", "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Firma", "ar": "شَرِكَةٌ", "pl": "شَرِكَاتٌ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Fabrik", "ar": "مَصْنَعٌ", "pl": "مَصَانِعُ", "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Antrag", "ar": "طَلَبٌ", "pl": "طَلَبَاتٌ", "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Ausbildung, Training", "ar": "تَدْرِيبٌ", "pl": "تَدْرِيبَاتٌ", "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Abteilung", "ar": "قِسْمٌ", "pl": "أَقْسَامٌ", "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Verantwortung", "ar": "مَسْؤُولِيَّةٌ", "pl": "مَسْؤُولِيَّاتٌ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Pause", "ar": "اِسْتِرَاحَةٌ", "pl": "اِسْتِرَاحَاتٌ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Wettbewerb", "ar": "مُسَابَقَةٌ", "pl": "مُسَابَقَاتٌ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Jahrhundert", "ar": "قَرْنٌ", "pl": "قُرُونٌ", "g": "m"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Seite (im Buch)", "ar": "صَفْحَةٌ", "pl": "صَفَحَاتٌ", "g": "f"},
    {"cat": "Studium und Arbeit", "type": "noun", "de": "Wörterbuch", "ar": "قَامُوسٌ", "pl": "قَوَامِيسُ", "g": "m"},

    # ================= Adjektive (Ergänzung) =================
    {"cat": "Adjektive", "type": "adjective", "de": "weich", "ar": "نَاعِمٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "hart, fest", "ar": "صُلْبٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "tief", "ar": "عَمِيقٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "hoch", "ar": "عَالٍ"},
    {"cat": "Adjektive", "type": "adjective", "de": "niedrig", "ar": "مُنْخَفِضٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "dick (Person)", "ar": "سَمِينٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "dünn (Person)", "ar": "نَحِيفٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "rund", "ar": "مُسْتَدِيرٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "gerade", "ar": "مُسْتَقِيمٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "voll", "ar": "مُمْتَلِئٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "laut", "ar": "صَاخِبٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "tot", "ar": "مَيِّتٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "wach", "ar": "مُسْتَيْقِظٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "sicher (ungefährlich)", "ar": "آمِنٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "gefährlich", "ar": "خَطِيرٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "nützlich", "ar": "مُفِيدٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "schädlich", "ar": "ضَارٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "unterhaltsam", "ar": "مُمْتِعٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "langweilig", "ar": "مُمِلٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "lustig", "ar": "مُضْحِكٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "ernst", "ar": "جَادٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "höflich", "ar": "مُؤَدَّبٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "freundlich, nett", "ar": "لَطِيفٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "großzügig", "ar": "كَرِيمٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "geizig", "ar": "بَخِيلٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "geduldig", "ar": "صَبُورٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "ehrlich", "ar": "صَادِقٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "treu", "ar": "وَفِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "mutig", "ar": "شُجَاعٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "feige", "ar": "جَبَانٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "stolz", "ar": "فَخُورٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "bescheiden", "ar": "مُتَوَاضِعٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "fleißig", "ar": "مُجْتَهِدٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "weise", "ar": "حَكِيمٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "verrückt", "ar": "مَجْنُونٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "modern", "ar": "عَصْرِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "traditionell", "ar": "تَقْلِيدِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "national", "ar": "وَطَنِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "international", "ar": "دَوْلِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "persönlich", "ar": "شَخْصِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "natürlich", "ar": "طَبِيعِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "künstlich, industriell", "ar": "صِنَاعِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "wissenschaftlich", "ar": "عِلْمِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "religiös", "ar": "دِينِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "politisch", "ar": "سِيَاسِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "wirtschaftlich", "ar": "اِقْتِصَادِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "gesellschaftlich", "ar": "اِجْتِمَاعِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "klar, deutlich", "ar": "وَاضِحٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "unklar", "ar": "غَامِضٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "sicher (überzeugt)", "ar": "مُتَأَكِّدٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "wahrscheinlich", "ar": "مُحْتَمَلٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "zufrieden", "ar": "رَاضٍ"},
    {"cat": "Adjektive", "type": "adjective", "de": "verheiratet", "ar": "مُتَزَوِّجٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "ledig", "ar": "أَعْزَبُ", "fem": "عَزْبَاءُ"},
    {"cat": "Adjektive", "type": "adjective", "de": "schwanger", "ar": "حَامِلٌ", "fem": None,
     "note": "nur für Frauen gebraucht, deshalb ohne ة"},
    {"cat": "Adjektive", "type": "adjective", "de": "blind", "ar": "أَعْمَى", "fem": "عَمْيَاءُ"},
    {"cat": "Adjektive", "type": "adjective", "de": "taub", "ar": "أَصَمُّ", "fem": "صَمَّاءُ"},
    {"cat": "Adjektive", "type": "adjective", "de": "scharf (Klinge)", "ar": "حَادٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "frisch", "ar": "طَازَجٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "verdorben", "ar": "فَاسِدٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "reif", "ar": "نَاضِجٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "roh", "ar": "نَيِّئٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "gekocht", "ar": "مَطْبُوخٌ"},
    {"cat": "Adjektive", "type": "adjective", "de": "gebraten", "ar": "مَقْلِيٌّ"},
    {"cat": "Adjektive", "type": "adjective", "de": "gegrillt", "ar": "مَشْوِيٌّ"},

    # ================= Kleine Wörter =================
    # Wörter, die in fast jedem Satz vorkommen. Sie beugen sich nicht,
    # deshalb stehen sie so da, wie man sie spricht.
    {"cat": "Kleine Wörter", "type": "phrase", "de": "sehr", "ar": "جِدًّا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "ein wenig", "ar": "قَلِيلًا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "fast", "ar": "تَقْرِيبًا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "genau", "ar": "بِالضَّبْطِ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "wirklich", "ar": "حَقًّا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "besonders", "ar": "خَاصَّةً"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "zum Beispiel", "ar": "مَثَلًا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "erstens, zuerst", "ar": "أَوَّلًا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "zweitens", "ar": "ثَانِيًا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "schließlich, zuletzt", "ar": "أَخِيرًا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "zusammen", "ar": "مَعًا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "allein", "ar": "وَحْدَهُ",
     "note": "beugt sich mit: وَحْدِي (allein – ich), وَحْدَكَ (du)"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "noch einmal", "ar": "مَرَّةً أُخْرَى"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "noch nicht", "ar": "لَيْسَ بَعْدُ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "schon, bereits", "ar": "بِالْفِعْلِ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "nur", "ar": "فَقَطْ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "mindestens", "ar": "عَلَى الْأَقَلِّ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "höchstens", "ar": "عَلَى الْأَكْثَرِ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "ungefähr", "ar": "حَوَالَيْ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "mehr", "ar": "أَكْثَرُ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "weniger", "ar": "أَقَلُّ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "besser", "ar": "أَفْضَلُ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "schlechter", "ar": "أَسْوَأُ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "draußen", "ar": "خَارِجًا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "drinnen", "ar": "دَاخِلًا"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "überall", "ar": "فِي كُلِّ مَكَانٍ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "jemand", "ar": "أَحَدٌ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "niemand", "ar": "لَا أَحَدَ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "nichts", "ar": "لَا شَيْءَ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "alles", "ar": "كُلُّ شَيْءٍ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "alle (Leute)", "ar": "اَلْجَمِيعُ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "jeder, jede", "ar": "كُلُّ",
     "note": "steht vor dem Nomen: كُلُّ يَوْمٍ – jeden Tag"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "einige", "ar": "بَعْضُ",
     "note": "steht vor dem Nomen: بَعْضُ النَّاسِ – einige Leute"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "trotzdem", "ar": "مَعَ ذَٰلِكَ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "leider", "ar": "لِلْأَسَفِ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "zum Glück", "ar": "لِحُسْنِ الْحَظِّ"},
    {"cat": "Kleine Wörter", "type": "phrase", "de": "plötzlich", "ar": "فَجْأَةً"},
]
